import { Express } from 'express';
import { productsRouter } from './products';
import { listingsRouter } from './listings';
import { jobsRouter } from './jobs';
import { healthRouter } from './health';
import { adminRouter } from './admin';
import { notificationsRouter } from './notifications';
import { categoriesRouter } from './categories';
import { templatesRouter } from './templates';
import { promptsRouter } from './prompts';
import { analyticsRouter } from './analytics';
import { inventoryRouter } from './inventory';
import { pricingRouter } from './pricing';
import { competitorsRouter } from './competitors';
import { rateLimitsRouter } from './rate-limits';
import { monitoringRouter } from './monitoring';
import { concurrencyRouter } from './concurrency';
import { authRouter } from './auth';
import { marketplacesRouter } from './marketplaces';
import { webhooksRouter } from './webhooks';
import { ordersRouter } from './orders';
import { notificationChannelsRouter } from './notification-channels';
import { alertsRouter } from './alerts';
import { realtimeRouter } from './realtime';
import { pricingOptimizerRouter } from './pricing-optimizer';
import { competitorMonitoringRouter } from './competitor-monitoring';
import { dashboardAnalyticsRouter } from './dashboard-analytics';
import { batchOperationsRouter } from './batch-operations';
import { scheduledReportsRouter } from './scheduled-reports';
import { settingsRouter } from './settings';
import { bulkOperationsRouter } from './bulk-operations';
import { refundsRouter } from './refunds';
import { shippingRouter } from './shipping';
import { performanceRouter } from './performance';
import { messageTemplatesRouter } from './message-templates';
import { customerMessagesRouter } from './customer-messages';
import { inventoryAlertsRouter } from './inventory-alerts';
import { salesAnalyticsRouter } from './sales-analytics';
import { exportsRouter } from './exports';
import { auditLogsRouter } from './audit-logs';
import { systemSettingsRouter } from './system-settings';
import { apiKeysRouter } from './api-keys';
import { usersRouter } from './users';
import { rolesRouter } from './roles';
import { webhookEndpointsRouter } from './webhook-endpoints';
import { backupsRouter } from './backups';
import { dashboardsRouter } from './dashboards';
import { notificationDispatchesRouter } from './notification-dispatches';
import { reportsRouter } from './reports';
import { batchJobsRouter } from './batch-jobs';
import { i18nRouter } from './i18n';
import { cacheRouter } from './cache';
import { metricsRouter } from './metrics';
import { securityRouter } from './security';
import { integrationsRouter } from './integrations';
import enrichmentRouter from './enrichment';
import joomRouter from './joom';
import joomCategoriesRouter from './joom-categories';
import uploadsRouter from './uploads';
import { shipmentsRouter } from './shipments';
import { sourcingRouter } from './sourcing';
import { cacheAdminRouter } from './cache-admin';
import { pricingAiRouter } from './pricing-ai';
import { customerSupportRouter } from './customer-support';
import { salesForecastRouter } from './sales-forecast';
import { queryPerformanceRouter } from './query-performance';
import { dashboardWidgetsRouter } from './dashboard-widgets';
import workflowRulesRouter from './workflow-rules';
import chatbotRouter from './chatbot';
import advancedAnalyticsRouter from './advanced-analytics';
import { abTestsRouter } from './ab-tests';
import { suppliersRouter } from './suppliers';
import { organizationsRouter } from './organizations';
import { inventoryForecastRouter } from './inventory-forecast';
import { externalIntegrationsRouter } from './external-integrations';
import { securityManagementRouter } from './security-management';
import { customerSuccessRouter } from './customer-success';
import { customReportsRouter } from './custom-reports';
import { ssoRouter } from './sso';
import { systemPerformanceRouter } from './system-performance';
import { multiCurrencyRouter } from './multi-currency';
import { complianceRouter } from './compliance';
import { advancedSearchRouter } from './advanced-search';
import { dataExportImportRouter } from './data-export-import';
import { webhookDeliveryRouter } from './webhook-delivery';
import { apiUsageRouter } from './api-usage';
import { backupRecoveryRouter } from './backup-recovery';
import { monitoringAlertsRouter } from './monitoring-alerts';
import { listingPerformanceRouter } from './listing-performance';
import { listingImprovementRouter } from './listing-improvement';
import { automationRulesRouter } from './automation-rules';
import { profitCalculationRouter } from './profit-calculation';
import etsyAuthRouter from './etsy-auth';
import etsyRouter from './etsy';
import shopifyRouter from './shopify';
import { shopifyAuthRouter } from './shopify-auth';


export function registerCoreRoutes(app: Express): void {
  app.use('/api/health', healthRouter);
  app.use('/api/products', productsRouter);
  app.use('/api/listings', listingsRouter);
  app.use('/api/jobs', jobsRouter);
  app.use('/api/admin', adminRouter);
  app.use('/api/notifications', notificationsRouter);
  app.use('/api/categories', categoriesRouter);
  app.use('/api/templates', templatesRouter);
  app.use('/api/prompts', promptsRouter);
  app.use('/api/analytics', analyticsRouter);
  app.use('/api/inventory', inventoryRouter);
  app.use('/api/pricing', pricingRouter);
  app.use('/api/competitors', competitorsRouter);
  app.use('/api/rate-limits', rateLimitsRouter);
  app.use('/api/monitoring', monitoringRouter);
  app.use('/api/concurrency', concurrencyRouter);
  app.use('/api/auth', authRouter);
  app.use('/api/marketplaces', marketplacesRouter);
  app.use('/api/webhooks', webhooksRouter);
  app.use('/api/orders', ordersRouter);
  app.use('/api/notification-channels', notificationChannelsRouter);
  app.use('/api/alerts', alertsRouter);
  app.use('/api/realtime', realtimeRouter);
  app.use('/api/pricing-optimizer', pricingOptimizerRouter);
  app.use('/api/competitor-monitoring', competitorMonitoringRouter);
  app.use('/api/dashboard', dashboardAnalyticsRouter);
  app.use('/api/batch', batchOperationsRouter);
  app.use('/api/scheduled-reports', scheduledReportsRouter);
  app.use('/api/settings', settingsRouter);
  app.use('/api/bulk', bulkOperationsRouter);
  app.use('/api/refunds', refundsRouter);
  app.use('/api/shipping', shippingRouter);
  app.use('/api/performance', performanceRouter);
  app.use('/api/message-templates', messageTemplatesRouter);
  app.use('/api/customer-messages', customerMessagesRouter);
  app.use('/api/inventory-alerts', inventoryAlertsRouter);
  app.use('/api/sales-analytics', salesAnalyticsRouter);
  app.use('/api/exports', exportsRouter);
  app.use('/api/audit-logs', auditLogsRouter);
  app.use('/api/system-settings', systemSettingsRouter);
  app.use('/api/api-keys', apiKeysRouter);
  app.use('/api/users', usersRouter);
  app.use('/api/roles', rolesRouter);
  app.use('/api/webhook-endpoints', webhookEndpointsRouter);
  app.use('/api/backups', backupsRouter);
  app.use('/api/dashboards', dashboardsRouter);
  app.use('/api/notification-dispatches', notificationDispatchesRouter);
  app.use('/api/reports', reportsRouter);
  app.use('/api/batch-jobs', batchJobsRouter);
  app.use('/api/i18n', i18nRouter);
  app.use('/api/cache', cacheRouter);
  app.use('/api/metrics', metricsRouter);
  app.use('/api/security', securityRouter);
  app.use('/api/integrations', integrationsRouter);
  app.use('/api/enrichment', enrichmentRouter);
  app.use('/api/joom', joomRouter);
  app.use('/api/joom-categories', joomCategoriesRouter);
  app.use('/api/uploads', uploadsRouter);
  app.use('/api/shipments', shipmentsRouter);
  app.use('/api/sourcing', sourcingRouter);
  app.use('/api/admin/cache', cacheAdminRouter);
  app.use('/api/pricing-ai', pricingAiRouter);
  app.use('/api/customer-support', customerSupportRouter);
  app.use('/api/sales-forecast', salesForecastRouter);
  app.use('/api/query-performance', queryPerformanceRouter);
  app.use('/api/dashboard-widgets', dashboardWidgetsRouter);
  app.use('/api/workflow-rules', workflowRulesRouter);
  app.use('/api/chatbot', chatbotRouter);
  app.use('/api/advanced-analytics', advancedAnalyticsRouter);
  app.use('/api/ab-tests', abTestsRouter);
  app.use('/api/suppliers', suppliersRouter);
  app.use('/api/organizations', organizationsRouter);
  app.use('/api/inventory-forecast', inventoryForecastRouter);
  app.use('/api/external-integrations', externalIntegrationsRouter);
  app.use('/api/security', securityManagementRouter);
  app.use('/api/customer-success', customerSuccessRouter);
  app.use('/api/custom-reports', customReportsRouter);
  app.use('/api/sso', ssoRouter);
  app.use('/api/system-performance', systemPerformanceRouter);
  app.use('/api/multi-currency', multiCurrencyRouter);
  app.use('/api/compliance', complianceRouter);
  app.use('/api/advanced-search', advancedSearchRouter);
  app.use('/api/data-export-import', dataExportImportRouter);
  app.use('/api/webhook-delivery', webhookDeliveryRouter);
  app.use('/api/api-usage', apiUsageRouter);
  app.use('/api/backup-recovery', backupRecoveryRouter);
  app.use('/api/monitoring-alerts', monitoringAlertsRouter);
  app.use('/api/listing-performance', listingPerformanceRouter);
  app.use('/api/listing-improvement', listingImprovementRouter);
  app.use('/api/automation-rules', automationRulesRouter);
  app.use('/api/profit-calculation', profitCalculationRouter);

  // v3.0: Etsy/Shopify OAuth認証
  app.use('/api/etsy', etsyAuthRouter);
  app.use('/api/etsy-listings', etsyRouter);
  app.use('/api/shopify-products', shopifyRouter);
  app.use('/api/shopify', shopifyAuthRouter);
}
