import { Express } from 'express';
import ebayAuthRouter from './ebay-auth';
import ebayListingsRouter from './ebay-listings';
import ebayTemplatesRouter from './ebay-templates';
import ebayBulkRouter from './ebay-bulk';
import ebayAutoRelistRouter from './ebay-auto-relist';
import ebayInventoryRouter from './ebay-inventory';
import ebaySalesRouter from './ebay-sales';
import ebayMessagesRouter from './ebay-messages';
import ebayOrdersRouter from './ebay-orders';
import ebayReturnsRouter from './ebay-returns';
import ebayFeedbackRouter from './ebay-feedback';
import ebayAnalyticsRouter from './ebay-analytics';
import ebayBulkEditorRouter from './ebay-bulk-editor';
import ebayCompetitorsRouter from './ebay-competitors';
import ebayAutoPricingRouter from './ebay-auto-pricing';
import ebayScheduledRouter from './ebay-scheduled';
import ebayAutoRestockRouter from './ebay-auto-restock';
import ebayOptimizationRouter from './ebay-optimization';
import { ebayABTestsRouter } from './ebay-ab-tests';
import { ebayMultilingualRouter } from './ebay-multilingual';
import { ebayPromotionsRouter } from './ebay-promotions';
import { ebayReportsRouter } from './ebay-reports';
import { ebayAdsRouter } from './ebay-ads';
import { ebayAutoMessagesRouter } from './ebay-auto-messages';
import { ebayFeedbackAnalysisRouter } from './ebay-feedback-analysis';
import { ebayLogisticsRouter } from './ebay-logistics';
import { ebayRecommendationsRouter } from './ebay-recommendations';
import { ebayBuyerSegmentsRouter } from './ebay-buyer-segments';
import { ebaySalesForecastRouter } from './ebay-sales-forecast';
import { ebayInventoryOptimizationRouter } from './ebay-inventory-optimization';
import { ebayCustomerLifecycleRouter } from './ebay-customer-lifecycle';
import { ebayDashboardRouter } from './ebay-dashboard';
import { ebayMultiStoreRouter } from './ebay-multi-store';
import { ebayApiMonitorRouter } from './ebay-api-monitor';
import { ebayProfitCalculatorRouter } from './ebay-profit-calculator';
import { ebayWorkflowsRouter } from './ebay-workflows';
import { ebayVariationsRouter } from './ebay-variations';
import { ebayBundlesRouter } from './ebay-bundles';
import { ebayShippingInternationalRouter } from './ebay-shipping-international';
import { ebaySellerHubRouter } from './ebay-seller-hub';
import { ebayCategoryMappingRouter } from './ebay-category-mapping';
import { ebayProductResearchRouter } from './ebay-product-research';
import { ebayMessageTemplatesRouter } from './ebay-message-templates';
import ebayShippingOptimizerRouter from './ebay-shipping-optimizer';
import ebayBuyerFeedbackRouter from './ebay-buyer-feedback';
import ebayPromotionManagerRouter from './ebay-promotion-manager';
import ebayTaxCalculatorRouter from './ebay-tax-calculator';
import ebaySupplierIntegrationRouter from './ebay-supplier-integration';
import ebayMultiWarehouseRouter from './ebay-multi-warehouse';
import ebayAbTestingRouter from './ebay-ab-testing';
import ebayCrossPlatformRouter from './ebay-cross-platform';
import ebayPerformanceDashboardRouter from './ebay-performance-dashboard';
import ebayBulkListerRouter from './ebay-bulk-lister';
import ebaySmartRepricingRouter from './ebay-smart-repricing';
import ebayOrderAutomationRouter from './ebay-order-automation';
import ebayCustomerInsightsRouter from './ebay-customer-insights';
import ebayListingSchedulerRouter from './ebay-listing-scheduler';
import ebayImageManagerRouter from './ebay-image-manager';
import ebayShippingCalculatorRouter from './ebay-shipping-calculator';
import ebayReturnManagerRouter from './ebay-return-manager';
import ebayPromotionEngineRouter from './ebay-promotion-engine';
import ebayFeeCalculatorRouter from './ebay-fee-calculator';
import ebayKeywordResearchRouter from './ebay-keyword-research';
import ebayCategoryExplorerRouter from './ebay-category-explorer';
import { ebayCustomerCommunicationRouter } from './ebay-customer-communication';
import { ebayInventoryAlertsRouter } from './ebay-inventory-alerts';
import { ebayReviewManagementRouter } from './ebay-review-management';
import { ebayShipmentTrackingRouter } from './ebay-shipment-tracking';
import { ebayAlertHubRouter } from './ebay-alert-hub';
import { ebayTemplatesV2Router } from './ebay-templates-v2';
import { ebaySeoOptimizerRouter } from './ebay-seo-optimizer';
import { ebayListingQualityRouter } from './ebay-listing-quality';
import { ebayTaxDutyRouter } from './ebay-tax-duty';
import { ebayBulkExportImportRouter } from './ebay-bulk-export-import';
import { ebayNotificationCenterRouter } from './ebay-notification-center';
import { ebayActivityLogRouter } from './ebay-activity-log';
import { ebayDataBackupRouter } from './ebay-data-backup';
import { ebayPerformanceMonitorRouter } from './ebay-performance-monitor';
import { ebayUserPreferencesRouter } from './ebay-user-preferences';
import { ebayHelpCenterRouter } from './ebay-help-center';
import { ebayWebhookManagerRouter } from './ebay-webhook-manager';
import { ebayApiKeysRouter } from './ebay-api-keys';
import { ebayAuditComplianceRouter } from './ebay-audit-compliance';
import { ebayMultiUserRouter } from './ebay-multi-user';
import { ebayAdvancedReportingRouter } from './ebay-advanced-reporting';
import { ebayDataVisualizationRouter } from './ebay-data-visualization';
import { ebayMlInsightsRouter } from './ebay-ml-insights';
import { ebayIntegrationHubRouter } from './ebay-integration-hub';
import { ebayMobileApiRouter } from './ebay-mobile-api';
import { ebayRealtimeCollabRouter } from './ebay-realtime-collab';
import { ebayCustomWorkflowsRouter } from './ebay-custom-workflows';
import { ebayAiAssistantRouter } from './ebay-ai-assistant';
import { ebayBulkImportExportRouter } from './ebay-bulk-import-export';
import { ebayNotificationCenterV2Router } from './ebay-notification-center-v2';
import { ebayCustomerSupportHubRouter } from './ebay-customer-support-hub';
import { ebayAdvancedSearchV2Router } from './ebay-advanced-search-v2';
import { ebaySecurityCenterRouter } from './ebay-security-center';
import { ebayDeveloperPortalRouter } from './ebay-developer-portal';
import { ebayAnalyticsDashboardV2Router } from './ebay-analytics-dashboard-v2';
import { ebayMultiLanguageV2Router } from './ebay-multi-language-v2';
import { ebayMarketplaceSyncRouter } from './ebay-marketplace-sync';
import { ebayInventoryHubRouter } from './ebay-inventory-hub';
import { ebayOrderFulfillmentRouter } from './ebay-order-fulfillment';
import { ebayPricingIntelligenceRouter } from './ebay-pricing-intelligence';
import { ebaySellerPerformanceRouter } from './ebay-seller-performance';
import { ebayProductCatalogRouter } from './ebay-product-catalog';
import { ebayShippingCalculatorRouter } from './ebay-shipping-calculator';
import { ebayTaxManagementRouter } from './ebay-tax-management';
import { ebaySupplierManagementRouter } from './ebay-supplier-management';
import { ebayReturnCenterRouter } from './ebay-return-center';
import { ebayMarketingHubRouter } from './ebay-marketing-hub';
import { ebayInventoryForecastingRouter } from './ebay-inventory-forecasting';
import { ebayCustomerAnalyticsRouter } from './ebay-customer-analytics';
import { ebayOrderAutomationRouter } from './ebay-order-automation';
import { ebayCompetitiveIntelligenceRouter } from './ebay-competitive-intelligence';
import ebayRevenueOptimizationRouter from './ebay-revenue-optimization';
import ebayFinancialReportingRouter from './ebay-financial-reporting';
import ebayBusinessAnalyticsRouter from './ebay-business-analytics';
import ebayCrossBorderHubRouter from './ebay-cross-border-hub';
import ebayQualityControlRouter from './ebay-quality-control';
import ebayStoreManagementRouter from './ebay-store-management';
import ebayWorkflowAutomationRouter from './ebay-workflow-automation';
import ebayInsightsDashboardRouter from './ebay-insights-dashboard';
import ebayAccountSettingsRouter from './ebay-account-settings';
import ebayComplianceCenterRouter from './ebay-compliance-center';
import ebayPerformanceAnalyticsRouter from './ebay-performance-analytics';
import ebayMarketIntelligenceRouter from './ebay-market-intelligence';
import ebayAutomationHubRouter from './ebay-automation-hub';
import ebayDataCenterRouter from './ebay-data-center';
import ebayIntegrationMarketplaceRouter from './ebay-integration-marketplace';
import ebaySmartSchedulerRouter from './ebay-smart-scheduler';
import ebayCustomerInsightsRouter from './ebay-customer-insights';
import ebayListingOptimizerRouter from './ebay-listing-optimizer';
import ebayOrderHubRouter from './ebay-order-hub';
import ebayShippingCenterRouter from './ebay-shipping-center';
import ebayPaymentGatewayRouter from './ebay-payment-gateway';
import ebayAnalyticsHubRouter from './ebay-analytics-hub';
import ebayReputationCenterRouter from './ebay-reputation-center';
import ebayDemandPlannerRouter from './ebay-demand-planner';
import ebayContentStudioRouter from './ebay-content-studio';
import ebayComplianceManagerRouter from './ebay-compliance-manager';
import ebaySupplierHubRouter from './ebay-supplier-hub';
import ebayReturnsManagerRouter from './ebay-returns-manager';
import ebayNotificationHubRouter from './ebay-notification-hub';
import ebayTaskManagerRouter from './ebay-task-manager';
import ebayListingCalendarRouter from './ebay-listing-calendar';
import ebayProfitDashboardRouter from './ebay-profit-dashboard';
import ebayInventoryAlertsV2Router from './ebay-inventory-alerts-v2';
import ebayCustomerServiceHubRouter from './ebay-customer-service-hub';
import ebayOrderTrackingHubRouter from './ebay-order-tracking-hub';
import ebayMarketplaceAnalyticsRouter from './ebay-marketplace-analytics';
import ebayBulkPricingManagerRouter from './ebay-bulk-pricing-manager';
import ebaySeoAnalyzerRouter from './ebay-seo-analyzer';
import ebayImageOptimizerRouter from './ebay-image-optimizer';
import ebayMultiCurrencyRouter from './ebay-multi-currency';
import ebayShippingLabelRouter from './ebay-shipping-label';
import ebayPriceHistoryRouter from './ebay-price-history';
import ebayInventorySyncHubRouter from './ebay-inventory-sync-hub';
import ebayListingAbTestManagerRouter from './ebay-listing-ab-test-manager';
import ebayReturnsDashboardProRouter from './ebay-returns-dashboard-pro';
import ebayInventorySnapshotToolRouter from './ebay-inventory-snapshot-tool';
import ebayShippingInsuranceManagerRouter from './ebay-shipping-insurance-manager';
import ebayListingExpiryTrackerRouter from './ebay-listing-expiry-tracker';
import ebayOrderConsolidationToolRouter from './ebay-order-consolidation-tool';
import ebayListingDraftManagerRouter from './ebay-listing-draft-manager';
import ebaySellerGoalTrackerRouter from './ebay-seller-goal-tracker';
import ebayPriceComparisonEngineRouter from './ebay-price-comparison-engine';
import ebayBulkDescriptionUpdaterRouter from './ebay-bulk-description-updater';
import ebayReturnLabelRouter from './ebay-return-label';
import ebayFeedbackResponseRouter from './ebay-feedback-response';
import ebaySalesPerformanceRouter from './ebay-sales-performance';
import ebayListingSchedulerRouter from './ebay-listing-scheduler';
import ebayCustomerInsightsV2Router from './ebay-customer-insights-v2';
import ebayBulkListingCreatorRouter from './ebay-bulk-listing-creator';
import ebayCompetitorTrackerProRouter from './ebay-competitor-tracker-pro';
import ebayProfitAnalyzerProRouter from './ebay-profit-analyzer-pro';
import ebayOrderWorkflowManagerRouter from './ebay-order-workflow-manager';
import ebaySkuGeneratorRouter from './ebay-sku-generator';
import ebayShippingRateCalculatorRouter from './ebay-shipping-rate-calculator';
import ebayProductSourcingHubRouter from './ebay-product-sourcing-hub';
import ebayQualityControlManagerRouter from './ebay-quality-control-manager';
import { ebayInventoryRestockPlannerRouter } from './ebay-inventory-restock-planner';
import { ebayCustomerCommunicationHubRouter } from './ebay-customer-communication-hub';
import { ebayDropshippingManagerRouter } from './ebay-dropshipping-manager';
import { ebaySupplierInvoiceManagerRouter } from './ebay-supplier-invoice-manager';
import { ebayProductBundleBuilderRouter } from './ebay-product-bundle-builder';
import { ebayWarrantyTrackerRouter } from './ebay-warranty-tracker';
import { ebayPhotoStudioManagerRouter } from './ebay-photo-studio-manager';
import { ebayTranslationHubRouter } from './ebay-translation-hub';
import { ebayCustomsDeclarationRouter } from './ebay-customs-declaration';
import { ebayBrandProtectionRouter } from './ebay-brand-protection';
import { ebayOrderDefectTrackerRouter } from './ebay-order-defect-tracker';
import { ebayGeographicSalesAnalyticsRouter } from './ebay-geographic-sales-analytics';
import { ebaySellerScoreOptimizerRouter } from './ebay-seller-score-optimizer';
import ebayReturnAutomationEngineRouter from './ebay-return-automation-engine';
import { ebayPriceElasticityAnalyzerRouter } from './ebay-price-elasticity-analyzer';
import { ebayReturnsPreventionRouter } from './ebay-returns-prevention';
import { ebayCustomerLoyaltyRouter } from './ebay-customer-loyalty';
import ebayListingTemplatesV3Router from './ebay-listing-templates-v3';
import ebayBuyerAnalyticsRouter from './ebay-buyer-analytics';
import ebaySupplyChainManagerRouter from './ebay-supply-chain-manager';
import ebayCompetitorTrackerRouter from './ebay-competitor-tracker';
import ebayReviewManagerRouter from './ebay-review-manager';
import ebayInventoryAlertsProRouter from './ebay-inventory-alerts-pro';
import ebaySalesVelocityRouter from './ebay-sales-velocity';
import ebayListingHealthRouter from './ebay-listing-health';
import ebayOrderDisputeRouter from './ebay-order-dispute';
import ebayBulkPriceEditorRouter from './ebay-bulk-price-editor';
import ebayShippingProfileRouter from './ebay-shipping-profile';
import ebayReturnPolicyRouter from './ebay-return-policy';
import ebaySkuManagementRouter from './ebay-sku-management';
import ebayShippingOptionsRouter from './ebay-shipping-options';
import ebayPaymentMethodsRouter from './ebay-payment-methods';
import ebaySellerMetricsRouter from './ebay-seller-metrics';
import ebayProductConditionRouter from './ebay-product-condition';
import ebayCategoryInsightsRouter from './ebay-category-insights';
import ebayListingAuditRouter from './ebay-listing-audit';
import ebayCrossSellRouter from './ebay-cross-sell';
import ebayStoreBrandingRouter from './ebay-store-branding';
import ebayInventorySyncRouter from './ebay-inventory-sync';
import ebayPriceAlertsRouter from './ebay-price-alerts';
import ebayBulkExportRouter from './ebay-bulk-export';
import ebayListingHealthV2Router from './ebay-listing-health-v2';
import ebayOrderInsightsRouter from './ebay-order-insights';
import ebayListingCloneRouter from './ebay-listing-clone';
import ebaySellerDashboardProRouter from './ebay-seller-dashboard-pro';
import ebayAutoResponderRouter from './ebay-auto-responder';
import ebayShippingLabelProRouter from './ebay-shipping-label-pro';
import ebayCategoryManagerRouter from './ebay-category-manager';
import ebayListingValidatorRouter from './ebay-listing-validator';
import ebaySalesReportRouter from './ebay-sales-report';
import ebayReturnAnalyticsRouter from './ebay-return-analytics';
import ebayListingOptimizerProRouter from './ebay-listing-optimizer-pro';
import ebayBuyerCommunicationHubRouter from './ebay-buyer-communication-hub';
import ebayInventoryForecasterRouter from './ebay-inventory-forecaster';
import ebayProfitTrackerRouter from './ebay-profit-tracker';
import ebayListingArchiveRouter from './ebay-listing-archive';
import ebayMarketplaceConnectorRouter from './ebay-marketplace-connector';
import ebayBulkUpdaterRouter from './ebay-bulk-updater';
import ebaySmartPricingRouter from './ebay-smart-pricing';
import ebayOrderTrackerProRouter from './ebay-order-tracker-pro';
import ebayStoreAnalyticsRouter from './ebay-store-analytics';
import ebayListingTemplateProRouter from './ebay-listing-template-pro';
import ebayDisputeManagerRouter from './ebay-dispute-manager';
import ebaySeoOptimizerRouter from './ebay-seo-optimizer';
import ebayPriceMonitorRouter from './ebay-price-monitor';
import ebayShippingAutomationRouter from './ebay-shipping-automation';
import ebayFeedbackAutomationRouter from './ebay-feedback-automation';
import ebayRevenueDashboardRouter from './ebay-revenue-dashboard';
import ebayCompetitorWatchRouter from './ebay-competitor-watch';
import ebayInventoryHubRouter from './ebay-inventory-hub';
import ebayListingScorerRouter from './ebay-listing-scorer';
import ebayOrderFulfillmentRouter from './ebay-order-fulfillment';
import ebayMultiChannelSyncRouter from './ebay-multi-channel-sync';
import ebayCustomerRetentionRouter from './ebay-customer-retention';
import ebayProductBundlerRouter from './ebay-product-bundler';
import ebayGlobalExpansionRouter from './ebay-global-expansion';
import ebayPolicyCheckerRouter from './ebay-policy-checker';
import ebaySalesAiPredictorRouter from './ebay-sales-ai-predictor';
import ebayInventoryRestockPlannerRouter from './ebay-inventory-restock-planner';
import ebayCustomerCommunicationHubRouter from './ebay-customer-communication-hub';
import ebayShippingRateComparatorRouter from './ebay-shipping-rate-comparator';
import ebayListingPerformanceTrackerRouter from './ebay-listing-performance-tracker';
import ebayOrderDisputeResolutionRouter from './ebay-order-dispute-resolution';
import ebayBulkListingSchedulerRouter from './ebay-bulk-listing-scheduler';
import ebayMarketplaceAnalyticsProRouter from './ebay-marketplace-analytics-pro';
import ebayProductSourcingAssistantRouter from './ebay-product-sourcing-assistant';
import ebayWarrantyManagerRouter from './ebay-warranty-manager';
import ebayInventoryValuationToolRouter from './ebay-inventory-valuation-tool';
import ebayCrossBorderTaxCalculatorRouter from './ebay-cross-border-tax-calculator';
import ebayItemSpecificsManagerRouter from './ebay-item-specifics-manager';
import ebayListingAnalyticsProRouter from './ebay-listing-analytics-pro';
import ebayPaymentReconciliationRouter from './ebay-payment-reconciliation';
import ebayDynamicPricingEngineRouter from './ebay-dynamic-pricing-engine';
import ebayCatalogManagementRouter from './ebay-catalog-management';
import ebayShippingTrackerProRouter from './ebay-shipping-tracker-pro';
import ebaySupplierScorecardRouter from './ebay-supplier-scorecard';
import ebayDemandForecasterRouter from './ebay-demand-forecaster';
import ebayMultiCurrencyManagerRouter from './ebay-multi-currency-manager';
import ebayListingComplianceCheckerRouter from './ebay-listing-compliance-checker';
import ebayOrderPriorityManagerRouter from './ebay-order-priority-manager';
import ebayPhotoEnhancementStudioRouter from './ebay-photo-enhancement-studio';
import ebaySalesChannelManagerRouter from './ebay-sales-channel-manager';
import ebayBuyerBehaviorAnalyticsRouter from './ebay-buyer-behavior-analytics';
import ebayInventoryAgingTrackerRouter from './ebay-inventory-aging-tracker';
import ebayCouponManagerRouter from './ebay-coupon-manager';
import ebayListingMigrationToolRouter from './ebay-listing-migration-tool';
import ebaySellerNotificationCenterRouter from './ebay-seller-notification-center';
import ebayProductVariationManagerRouter from './ebay-product-variation-manager';
import ebayRevenueForecasterRouter from './ebay-revenue-forecaster';
import ebayBulkImageUploaderRouter from './ebay-bulk-image-uploader';
import ebayCustomReportBuilderRouter from './ebay-custom-report-builder';
import ebayPackagingManagerRouter from './ebay-packaging-manager';
import ebayMarketplaceFeeOptimizerRouter from './ebay-marketplace-fee-optimizer';
import ebaySellerComplianceDashboardRouter from './ebay-seller-compliance-dashboard';
import ebayAbandonedCartRecoveryRouter from './ebay-abandoned-cart-recovery';
import ebayCrossPromotionEngineRouter from './ebay-cross-promotion-engine';
import ebaySellerBenchmarkingRouter from './ebay-seller-benchmarking';
import ebayInventoryTransferManagerRouter from './ebay-inventory-transfer-manager';
import ebayAiProductDescriptionGeneratorRouter from './ebay-ai-product-description-generator';
import ebayListingWatermarkToolRouter from './ebay-listing-watermark-tool';
import ebayOrderBatchProcessorRouter from './ebay-order-batch-processor';
import ebayKeywordRankTrackerRouter from './ebay-keyword-rank-tracker';
import ebaySupplierOrderTrackerRouter from './ebay-supplier-order-tracker';
import ebayListingSeoAuditRouter from './ebay-listing-seo-audit';
import ebayStoreThemeCustomizerRouter from './ebay-store-theme-customizer';
import ebayProfitMarginCalculatorRouter from './ebay-profit-margin-calculator';
import ebayListingRotationSchedulerRouter from './ebay-listing-rotation-scheduler';
import ebayCustomerFeedbackLoopRouter from './ebay-customer-feedback-loop';
import ebaySmartInventoryAllocatorRouter from './ebay-smart-inventory-allocator';
import ebayWarehousePickingOptimizerRouter from './ebay-warehouse-picking-optimizer';
import ebayProductLifecycleManagerRouter from './ebay-product-lifecycle-manager';
import ebaySellerTaxReportGeneratorRouter from './ebay-seller-tax-report-generator';
import ebayListingQualityScorerProRouter from './ebay-listing-quality-scorer-pro';
import ebayMultiAccountManagerRouter from './ebay-multi-account-manager';
import ebayOrderGiftWrapperRouter from './ebay-order-gift-wrapper';
import ebayInventoryCountSchedulerRouter from './ebay-inventory-count-scheduler';
import ebaySellerOnboardingWizardRouter from './ebay-seller-onboarding-wizard';
import ebayListingImpressionTrackerRouter from './ebay-listing-impression-tracker';
import ebayAutomatedRepricingBotRouter from './ebay-automated-repricing-bot';
// Phase 431-435
import ebayShippingZoneManagerRouter from './ebay-shipping-zone-manager';
import ebayProductTagManagerRouter from './ebay-product-tag-manager';
import ebayOrderRiskScorerRouter from './ebay-order-risk-scorer';
import ebayListingFreshnessMonitorRouter from './ebay-listing-freshness-monitor';
import ebayCarrierPerformanceTrackerRouter from './ebay-carrier-performance-tracker';
// Phase 436-440
import ebayInventoryShrinkageTrackerRouter from './ebay-inventory-shrinkage-tracker';
import ebaySellerReputationGuardRouter from './ebay-seller-reputation-guard';
import ebayListingConversionOptimizerRouter from './ebay-listing-conversion-optimizer';
import ebayOrderRoutingEngineRouter from './ebay-order-routing-engine';
import ebayProductReviewAggregatorRouter from './ebay-product-review-aggregator';
// Phase 441-445
import ebayListingCalendarRouter from './ebay-listing-calendar';
import ebayOrderEscalationManagerRouter from './ebay-order-escalation-manager';
import ebayProductAuthenticationBadgeRouter from './ebay-product-authentication-badge';
import ebaySellerCommunityHubRouter from './ebay-seller-community-hub';
import ebayInventoryReservationManagerRouter from './ebay-inventory-reservation-manager';
// Phase 446-450
import ebaySmartBundleCreatorRouter from './ebay-smart-bundle-creator';
import ebayListingHealthMonitorProRouter from './ebay-listing-health-monitor-pro';
import ebayOrderDeliveryTrackerRouter from './ebay-order-delivery-tracker';
import ebayProductCatalogEnrichmentRouter from './ebay-product-catalog-enrichment';
import ebaySellerPerformanceOptimizerRouter from './ebay-seller-performance-optimizer';
// Phase 451-455
import ebayReturnLabelGeneratorRouter from './ebay-return-label-generator';
import ebayCompetitorPriceAlertRouter from './ebay-competitor-price-alert';
import ebayShippingCostSplitterRouter from './ebay-shipping-cost-splitter';
import ebayProductConditionGraderRouter from './ebay-product-condition-grader';
import ebayOrderFulfillmentOptimizerRouter from './ebay-order-fulfillment-optimizer';
// Phase 456-460
import ebayListingImageAiOptimizerRouter from './ebay-listing-image-ai-optimizer';
import ebayBuyerLoyaltyProgramRouter from './ebay-buyer-loyalty-program';
import ebayInventoryDemandPlannerRouter from './ebay-inventory-demand-planner';
import ebayListingTranslationHubRouter from './ebay-listing-translation-hub';
import ebaySellerFinancialDashboardRouter from './ebay-seller-financial-dashboard';
// Phase 461-465
import ebayOrderCancellationManagerRouter from './ebay-order-cancellation-manager';
import ebayListingCategoryAdvisorRouter from './ebay-listing-category-advisor';
import ebaySellerPayoutTrackerRouter from './ebay-seller-payout-tracker';
import ebayProductCrossReferenceToolRouter from './ebay-product-cross-reference-tool';
import ebayListingPromotionSchedulerRouter from './ebay-listing-promotion-scheduler';


export function registerEbayRoutes(app: Express): void {
  app.use('/api/ebay', ebayAuthRouter);
  app.use('/api/ebay-listings', ebayListingsRouter);
  app.use('/api/ebay-templates', ebayTemplatesRouter);
  app.use('/api/ebay-bulk', ebayBulkRouter);
  app.use('/api/ebay-auto-relist', ebayAutoRelistRouter);
  app.use('/api/ebay-inventory', ebayInventoryRouter);
  app.use('/api/ebay-sales', ebaySalesRouter);
  app.use('/api/ebay-messages', ebayMessagesRouter);
  app.use('/api/ebay-orders', ebayOrdersRouter);
  app.use('/api/ebay-returns', ebayReturnsRouter);
  app.use('/api/ebay-feedback', ebayFeedbackRouter);
  app.use('/api/ebay-analytics', ebayAnalyticsRouter);
  app.use('/api/ebay-bulk-editor', ebayBulkEditorRouter);
  app.use('/api/ebay-competitors', ebayCompetitorsRouter);
  app.use('/api/ebay-auto-pricing', ebayAutoPricingRouter);
  app.use('/api/ebay-scheduled', ebayScheduledRouter);
  app.use('/api/ebay-auto-restock', ebayAutoRestockRouter);
  app.use('/api/ebay-optimization', ebayOptimizationRouter);
  app.use('/api/ebay-ab-tests', ebayABTestsRouter);
  app.use('/api/ebay-multilingual', ebayMultilingualRouter);
  app.use('/api/ebay-promotions', ebayPromotionsRouter);
  app.use('/api/ebay-reports', ebayReportsRouter);
  app.use('/api/ebay-ads', ebayAdsRouter);
  app.use('/api/ebay-auto-messages', ebayAutoMessagesRouter);
  app.use('/api/ebay-feedback-analysis', ebayFeedbackAnalysisRouter);
  app.use('/api/ebay-logistics', ebayLogisticsRouter);
  app.use('/api/ebay-recommendations', ebayRecommendationsRouter);
  app.use('/api/ebay-buyer-segments', ebayBuyerSegmentsRouter);
  app.use('/api/ebay-sales-forecast', ebaySalesForecastRouter);
  app.use('/api/ebay-inventory-optimization', ebayInventoryOptimizationRouter);
  app.use('/api/ebay-customer-lifecycle', ebayCustomerLifecycleRouter);
  app.use('/api/ebay-dashboard', ebayDashboardRouter);
  app.use('/api/ebay-multi-store', ebayMultiStoreRouter);
  app.use('/api/ebay-api-monitor', ebayApiMonitorRouter);
  app.use('/api/ebay-profit-calculator', ebayProfitCalculatorRouter);
  app.use('/api/ebay-workflows', ebayWorkflowsRouter);
  app.use('/api/ebay-variations', ebayVariationsRouter);
  app.use('/api/ebay-bundles', ebayBundlesRouter);
  app.use('/api/ebay-shipping-international', ebayShippingInternationalRouter);
  app.use('/api/ebay-seller-hub', ebaySellerHubRouter);
  app.use('/api/ebay-category-mapping', ebayCategoryMappingRouter);
  app.use('/api/ebay-product-research', ebayProductResearchRouter);
  app.use('/api/ebay-message-templates', ebayMessageTemplatesRouter);
  app.use('/api/ebay-shipping-optimizer', ebayShippingOptimizerRouter);
  app.use('/api/ebay-buyer-feedback', ebayBuyerFeedbackRouter);
  app.use('/api/ebay-promotion-manager', ebayPromotionManagerRouter);
  app.use('/api/ebay-tax-calculator', ebayTaxCalculatorRouter);
  app.use('/api/ebay-supplier-integration', ebaySupplierIntegrationRouter);
  app.use('/api/ebay-multi-warehouse', ebayMultiWarehouseRouter);
  app.use('/api/ebay-ab-testing', ebayAbTestingRouter);
  app.use('/api/ebay-cross-platform', ebayCrossPlatformRouter);
  app.use('/api/ebay-performance-dashboard', ebayPerformanceDashboardRouter);
  app.use('/api/ebay-bulk-lister', ebayBulkListerRouter);
  app.use('/api/ebay-smart-repricing', ebaySmartRepricingRouter);
  app.use('/api/ebay-order-automation', ebayOrderAutomationRouter);
  app.use('/api/ebay-customer-insights', ebayCustomerInsightsRouter);
  app.use('/api/ebay-listing-scheduler', ebayListingSchedulerRouter);
  app.use('/api/ebay-image-manager', ebayImageManagerRouter);
  app.use('/api/ebay-shipping-calculator', ebayShippingCalculatorRouter);
  app.use('/api/ebay-return-manager', ebayReturnManagerRouter);
  app.use('/api/ebay-promotion-engine', ebayPromotionEngineRouter);
  app.use('/api/ebay-fee-calculator', ebayFeeCalculatorRouter);
  app.use('/api/ebay-keyword-research', ebayKeywordResearchRouter);
  app.use('/api/ebay-category-explorer', ebayCategoryExplorerRouter);
  app.use('/api/ebay-customer-communication', ebayCustomerCommunicationRouter);
  app.use('/api/ebay-inventory-alerts', ebayInventoryAlertsRouter);
  app.use('/api/ebay-review-management', ebayReviewManagementRouter);
  app.use('/api/ebay-shipment-tracking', ebayShipmentTrackingRouter);
  app.use('/api/ebay-alert-hub', ebayAlertHubRouter);
  app.use('/api/ebay-templates-v2', ebayTemplatesV2Router);
  app.use('/api/ebay-seo-optimizer', ebaySeoOptimizerRouter);
  app.use('/api/ebay-listing-quality', ebayListingQualityRouter);
  app.use('/api/ebay-tax-duty', ebayTaxDutyRouter);
  app.use('/api/ebay-bulk-export-import', ebayBulkExportImportRouter);
  app.use('/api/ebay-notification-center', ebayNotificationCenterRouter);
  app.use('/api/ebay-activity-log', ebayActivityLogRouter);
  app.use('/api/ebay-data-backup', ebayDataBackupRouter);
  app.use('/api/ebay-performance-monitor', ebayPerformanceMonitorRouter);
  app.use('/api/ebay-user-preferences', ebayUserPreferencesRouter);
  app.use('/api/ebay-help-center', ebayHelpCenterRouter);
  app.use('/api/ebay-webhook-manager', ebayWebhookManagerRouter);
  app.use('/api/ebay-api-keys', ebayApiKeysRouter);
  app.use('/api/ebay-audit-compliance', ebayAuditComplianceRouter);
  app.use('/api/ebay-multi-user', ebayMultiUserRouter);
  app.use('/api/ebay-advanced-reporting', ebayAdvancedReportingRouter);
  app.use('/api/ebay-data-visualization', ebayDataVisualizationRouter);
  app.use('/api/ebay-ml-insights', ebayMlInsightsRouter);
  app.use('/api/ebay-integration-hub', ebayIntegrationHubRouter);
  app.use('/api/ebay-mobile-api', ebayMobileApiRouter);
  app.use('/api/ebay-realtime-collab', ebayRealtimeCollabRouter);
  app.use('/api/ebay-custom-workflows', ebayCustomWorkflowsRouter);
  app.use('/api/ebay-ai-assistant', ebayAiAssistantRouter);
  app.use('/api/ebay-bulk-import-export', ebayBulkImportExportRouter);
  app.use('/api/ebay-notification-center-v2', ebayNotificationCenterV2Router);
  app.use('/api/ebay-customer-support-hub', ebayCustomerSupportHubRouter);
  app.use('/api/ebay-advanced-search-v2', ebayAdvancedSearchV2Router);
  app.use('/api/ebay-security-center', ebaySecurityCenterRouter);
  app.use('/api/ebay-developer-portal', ebayDeveloperPortalRouter);
  app.use('/api/ebay-analytics-dashboard-v2', ebayAnalyticsDashboardV2Router);
  app.use('/api/ebay-multi-language-v2', ebayMultiLanguageV2Router);
  app.use('/api/ebay-marketplace-sync', ebayMarketplaceSyncRouter);
  app.use('/api/ebay-inventory-hub', ebayInventoryHubRouter);
  app.use('/api/ebay-order-fulfillment', ebayOrderFulfillmentRouter);
  app.use('/api/ebay-pricing-intelligence', ebayPricingIntelligenceRouter);
  app.use('/api/ebay-seller-performance', ebaySellerPerformanceRouter);
  app.use('/api/ebay-product-catalog', ebayProductCatalogRouter);
  app.use('/api/ebay-shipping-calculator', ebayShippingCalculatorRouter);
  app.use('/api/ebay-tax-management', ebayTaxManagementRouter);
  app.use('/api/ebay-supplier-management', ebaySupplierManagementRouter);
  app.use('/api/ebay-return-center', ebayReturnCenterRouter);
  app.use('/api/ebay-marketing-hub', ebayMarketingHubRouter);
  app.use('/api/ebay-inventory-forecasting', ebayInventoryForecastingRouter);
  app.use('/api/ebay-customer-analytics', ebayCustomerAnalyticsRouter);
  app.use('/api/ebay-order-automation', ebayOrderAutomationRouter);
  app.use('/api/ebay-competitive-intelligence', ebayCompetitiveIntelligenceRouter);
  app.use('/api/ebay/revenue-optimization', ebayRevenueOptimizationRouter);
  app.use('/api/ebay/financial-reporting', ebayFinancialReportingRouter);
  app.use('/api/ebay/business-analytics', ebayBusinessAnalyticsRouter);
  app.use('/api/ebay/cross-border-hub', ebayCrossBorderHubRouter);
  app.use('/api/ebay/quality-control', ebayQualityControlRouter);
  app.use('/api/ebay/store-management', ebayStoreManagementRouter);
  app.use('/api/ebay/workflow-automation', ebayWorkflowAutomationRouter);
  app.use('/api/ebay/insights-dashboard', ebayInsightsDashboardRouter);
  app.use('/api/ebay/account-settings', ebayAccountSettingsRouter);
  app.use('/api/ebay/compliance-center', ebayComplianceCenterRouter);
  app.use('/api/ebay/performance-analytics', ebayPerformanceAnalyticsRouter);
  app.use('/api/ebay/market-intelligence', ebayMarketIntelligenceRouter);
  app.use('/api/ebay/automation-hub', ebayAutomationHubRouter);
  app.use('/api/ebay/data-center', ebayDataCenterRouter);
  app.use('/api/ebay/integration-marketplace', ebayIntegrationMarketplaceRouter);
  app.use('/api/ebay/smart-scheduler', ebaySmartSchedulerRouter);
  app.use('/api/ebay/customer-insights', ebayCustomerInsightsRouter);
  app.use('/api/ebay/listing-optimizer', ebayListingOptimizerRouter);
  app.use('/api/ebay/order-hub', ebayOrderHubRouter);
  app.use('/api/ebay/shipping-center', ebayShippingCenterRouter);
  app.use('/api/ebay/payment-gateway', ebayPaymentGatewayRouter);
  app.use('/api/ebay/analytics-hub', ebayAnalyticsHubRouter);
  app.use('/api/ebay/reputation-center', ebayReputationCenterRouter);
  app.use('/api/ebay/demand-planner', ebayDemandPlannerRouter);
  app.use('/api/ebay/content-studio', ebayContentStudioRouter);
  app.use('/api/ebay/compliance-manager', ebayComplianceManagerRouter);
  app.use('/api/ebay/supplier-hub', ebaySupplierHubRouter);
  app.use('/api/ebay/returns-manager', ebayReturnsManagerRouter);
  app.use('/api/ebay/notification-hub', ebayNotificationHubRouter);
  app.use('/api/ebay/task-manager', ebayTaskManagerRouter);
  app.use('/api/ebay/listing-calendar', ebayListingCalendarRouter);
  app.use('/api/ebay/profit-dashboard', ebayProfitDashboardRouter);
  app.use('/api/ebay/inventory-alerts-v2', ebayInventoryAlertsV2Router);
  app.use('/api/ebay/customer-service-hub', ebayCustomerServiceHubRouter);
  app.use('/api/ebay/order-tracking-hub', ebayOrderTrackingHubRouter);
  app.use('/api/ebay/marketplace-analytics', ebayMarketplaceAnalyticsRouter);
  app.use('/api/ebay/bulk-pricing-manager', ebayBulkPricingManagerRouter);
  app.use('/api/ebay/seo-analyzer', ebaySeoAnalyzerRouter);
  app.use('/api/ebay/image-optimizer', ebayImageOptimizerRouter);
  app.use('/api/ebay/multi-currency', ebayMultiCurrencyRouter);
  app.use('/api/ebay/shipping-label', ebayShippingLabelRouter);
  app.use('/api/ebay/price-history', ebayPriceHistoryRouter);
  app.use('/api/ebay/inventory-sync-hub', ebayInventorySyncHubRouter);
  app.use('/api/ebay/return-label', ebayReturnLabelRouter);
  app.use('/api/ebay/feedback-response', ebayFeedbackResponseRouter);
  app.use('/api/ebay/sales-performance', ebaySalesPerformanceRouter);
  app.use('/api/ebay/listing-scheduler', ebayListingSchedulerRouter);
  app.use('/api/ebay/customer-insights-v2', ebayCustomerInsightsV2Router);
  app.use('/api/ebay/bulk-listing-creator', ebayBulkListingCreatorRouter);
  app.use('/api/ebay/competitor-tracker-pro', ebayCompetitorTrackerProRouter);
  app.use('/api/ebay/profit-analyzer-pro', ebayProfitAnalyzerProRouter);
  app.use('/api/ebay/order-workflow-manager', ebayOrderWorkflowManagerRouter);
  app.use('/api/ebay/sku-generator', ebaySkuGeneratorRouter);
  app.use('/api/ebay/shipping-rate-calculator', ebayShippingRateCalculatorRouter);
  app.use('/api/ebay/product-sourcing-hub', ebayProductSourcingHubRouter);
  app.use('/api/ebay/quality-control-manager', ebayQualityControlManagerRouter);
  app.use('/api/ebay/inventory-restock-planner', ebayInventoryRestockPlannerRouter);
  app.use('/api/ebay/customer-communication-hub', ebayCustomerCommunicationHubRouter);
  app.use('/api/ebay/dropshipping-manager', ebayDropshippingManagerRouter);
  app.use('/api/ebay/supplier-invoice-manager', ebaySupplierInvoiceManagerRouter);
  app.use('/api/ebay/product-bundle-builder', ebayProductBundleBuilderRouter);
  app.use('/api/ebay/warranty-tracker', ebayWarrantyTrackerRouter);
  app.use('/api/ebay/photo-studio-manager', ebayPhotoStudioManagerRouter);
  app.use('/api/ebay/translation-hub', ebayTranslationHubRouter);
  app.use('/api/ebay/customs-declaration', ebayCustomsDeclarationRouter);
  app.use('/api/ebay/brand-protection', ebayBrandProtectionRouter);
  app.use('/api/ebay/order-defect-tracker', ebayOrderDefectTrackerRouter);
  app.use('/api/ebay/geographic-sales-analytics', ebayGeographicSalesAnalyticsRouter);
  app.use('/api/ebay/seller-score-optimizer', ebaySellerScoreOptimizerRouter);
  // Alias base for Phase 362 web page
  app.use('/api/ebay-seller-score-optimizer', ebaySellerScoreOptimizerRouter);
  // Return Automation Engine (Phase 361)
  app.use('/api/ebay-return-automation-engine', ebayReturnAutomationEngineRouter);
  app.use('/api/ebay/price-elasticity-analyzer', ebayPriceElasticityAnalyzerRouter);
  app.use('/api/ebay/returns-prevention', ebayReturnsPreventionRouter);
  app.use('/api/ebay/customer-loyalty', ebayCustomerLoyaltyRouter);
  app.use('/api/ebay-listing-templates-v3', ebayListingTemplatesV3Router);
  app.use('/api/ebay-buyer-analytics', ebayBuyerAnalyticsRouter);
  app.use('/api/ebay-supply-chain-manager', ebaySupplyChainManagerRouter);
  app.use('/api/ebay-competitor-tracker', ebayCompetitorTrackerRouter);
  app.use('/api/ebay-review-manager', ebayReviewManagerRouter);
  app.use('/api/ebay-inventory-alerts-pro', ebayInventoryAlertsProRouter);
  app.use('/api/ebay-sales-velocity', ebaySalesVelocityRouter);
  app.use('/api/ebay-listing-health', ebayListingHealthRouter);
  app.use('/api/ebay-order-dispute', ebayOrderDisputeRouter);
  app.use('/api/ebay-bulk-price-editor', ebayBulkPriceEditorRouter);
  app.use('/api/ebay-shipping-profile', ebayShippingProfileRouter);
  app.use('/api/ebay-return-policy', ebayReturnPolicyRouter);
  app.use('/api/ebay-sku-management', ebaySkuManagementRouter);
  app.use('/api/ebay-shipping-options', ebayShippingOptionsRouter);
  app.use('/api/ebay-payment-methods', ebayPaymentMethodsRouter);
  app.use('/api/ebay-seller-metrics', ebaySellerMetricsRouter);
  app.use('/api/ebay-product-condition', ebayProductConditionRouter);
  app.use('/api/ebay-category-insights', ebayCategoryInsightsRouter);
  app.use('/api/ebay-listing-audit', ebayListingAuditRouter);
  app.use('/api/ebay-cross-sell', ebayCrossSellRouter);
  app.use('/api/ebay-store-branding', ebayStoreBrandingRouter);
  app.use('/api/ebay-inventory-sync', ebayInventorySyncRouter);
  app.use('/api/ebay-price-alerts', ebayPriceAlertsRouter);
  app.use('/api/ebay-bulk-export', ebayBulkExportRouter);
  app.use('/api/ebay-listing-health-v2', ebayListingHealthV2Router);
  app.use('/api/ebay-order-insights', ebayOrderInsightsRouter);
  app.use('/api/ebay-listing-clone', ebayListingCloneRouter);
  app.use('/api/ebay-seller-dashboard-pro', ebaySellerDashboardProRouter);
  app.use('/api/ebay-auto-responder', ebayAutoResponderRouter);
  app.use('/api/ebay-shipping-label-pro', ebayShippingLabelProRouter);
  app.use('/api/ebay-category-manager', ebayCategoryManagerRouter);
  app.use('/api/ebay-listing-validator', ebayListingValidatorRouter);
  app.use('/api/ebay-sales-report', ebaySalesReportRouter);
  app.use('/api/ebay-return-analytics', ebayReturnAnalyticsRouter);
  app.use('/api/ebay-listing-optimizer-pro', ebayListingOptimizerProRouter);
  app.use('/api/ebay-buyer-communication-hub', ebayBuyerCommunicationHubRouter);
  app.use('/api/ebay-inventory-forecaster', ebayInventoryForecasterRouter);
  app.use('/api/ebay-profit-tracker', ebayProfitTrackerRouter);
  app.use('/api/ebay-listing-archive', ebayListingArchiveRouter);
  app.use('/api/ebay-marketplace-connector', ebayMarketplaceConnectorRouter);
  app.use('/api/ebay-bulk-updater', ebayBulkUpdaterRouter);
  app.use('/api/ebay-smart-pricing', ebaySmartPricingRouter);
  app.use('/api/ebay-order-tracker-pro', ebayOrderTrackerProRouter);
  app.use('/api/ebay-store-analytics', ebayStoreAnalyticsRouter);
  app.use('/api/ebay-listing-template-pro', ebayListingTemplateProRouter);
  app.use('/api/ebay-dispute-manager', ebayDisputeManagerRouter);
  app.use('/api/ebay-seo-optimizer', ebaySeoOptimizerRouter);
  app.use('/api/ebay-price-monitor', ebayPriceMonitorRouter);
  app.use('/api/ebay-shipping-automation', ebayShippingAutomationRouter);
  app.use('/api/ebay-feedback-automation', ebayFeedbackAutomationRouter);
  app.use('/api/ebay-revenue-dashboard', ebayRevenueDashboardRouter);
  app.use('/api/ebay-competitor-watch', ebayCompetitorWatchRouter);
  app.use('/api/ebay-inventory-hub', ebayInventoryHubRouter);
  app.use('/api/ebay-listing-scorer', ebayListingScorerRouter);
  app.use('/api/ebay-order-fulfillment', ebayOrderFulfillmentRouter);
  app.use('/api/ebay-multi-channel-sync', ebayMultiChannelSyncRouter);
  app.use('/api/ebay-customer-retention', ebayCustomerRetentionRouter);
  app.use('/api/ebay-product-bundler', ebayProductBundlerRouter);
  app.use('/api/ebay-global-expansion', ebayGlobalExpansionRouter);
  app.use('/api/ebay-policy-checker', ebayPolicyCheckerRouter);
  app.use('/api/ebay-sales-ai-predictor', ebaySalesAiPredictorRouter);
  app.use('/api/ebay-inventory-restock-planner', ebayInventoryRestockPlannerRouter);
  app.use('/api/ebay-customer-communication-hub', ebayCustomerCommunicationHubRouter);
  app.use('/api/ebay-shipping-rate-comparator', ebayShippingRateComparatorRouter);
  app.use('/api/ebay-listing-performance-tracker', ebayListingPerformanceTrackerRouter);
  app.use('/api/ebay-order-dispute-resolution', ebayOrderDisputeResolutionRouter);
  app.use('/api/ebay-product-sourcing-assistant', ebayProductSourcingAssistantRouter);
  app.use('/api/ebay-bulk-listing-scheduler', ebayBulkListingSchedulerRouter);
  app.use('/api/ebay-marketplace-analytics-pro', ebayMarketplaceAnalyticsProRouter);
  // Phase 368-370
  app.use('/api/ebay-warranty-manager', ebayWarrantyManagerRouter);
  app.use('/api/ebay-inventory-valuation-tool', ebayInventoryValuationToolRouter);
  app.use('/api/ebay-cross-border-tax-calculator', ebayCrossBorderTaxCalculatorRouter);
  // Phase 371-375
  app.use('/api/ebay-item-specifics-manager', ebayItemSpecificsManagerRouter);
  app.use('/api/ebay-listing-analytics-pro', ebayListingAnalyticsProRouter);
  app.use('/api/ebay-payment-reconciliation', ebayPaymentReconciliationRouter);
  app.use('/api/ebay-dynamic-pricing-engine', ebayDynamicPricingEngineRouter);
  app.use('/api/ebay-catalog-management', ebayCatalogManagementRouter);
  // Phase 376-380
  app.use('/api/ebay-shipping-tracker-pro', ebayShippingTrackerProRouter);
  app.use('/api/ebay-supplier-scorecard', ebaySupplierScorecardRouter);
  app.use('/api/ebay-demand-forecaster', ebayDemandForecasterRouter);
  app.use('/api/ebay-multi-currency-manager', ebayMultiCurrencyManagerRouter);
  app.use('/api/ebay-listing-compliance-checker', ebayListingComplianceCheckerRouter);
  // Phase 381-385
  app.use('/api/ebay-order-priority-manager', ebayOrderPriorityManagerRouter);
  app.use('/api/ebay-photo-enhancement-studio', ebayPhotoEnhancementStudioRouter);
  app.use('/api/ebay-sales-channel-manager', ebaySalesChannelManagerRouter);
  app.use('/api/ebay-buyer-behavior-analytics', ebayBuyerBehaviorAnalyticsRouter);
  app.use('/api/ebay-inventory-aging-tracker', ebayInventoryAgingTrackerRouter);
  // Phase 386-390
  app.use('/api/ebay-coupon-manager', ebayCouponManagerRouter);
  app.use('/api/ebay-listing-migration-tool', ebayListingMigrationToolRouter);
  app.use('/api/ebay-seller-notification-center', ebaySellerNotificationCenterRouter);
  app.use('/api/ebay-product-variation-manager', ebayProductVariationManagerRouter);
  app.use('/api/ebay-revenue-forecaster', ebayRevenueForecasterRouter);
  // Phase 391-395
  app.use('/api/ebay-bulk-image-uploader', ebayBulkImageUploaderRouter);
  app.use('/api/ebay-custom-report-builder', ebayCustomReportBuilderRouter);
  app.use('/api/ebay-packaging-manager', ebayPackagingManagerRouter);
  app.use('/api/ebay-marketplace-fee-optimizer', ebayMarketplaceFeeOptimizerRouter);
  app.use('/api/ebay-seller-compliance-dashboard', ebaySellerComplianceDashboardRouter);
  // Phase 396-400
  app.use('/api/ebay-abandoned-cart-recovery', ebayAbandonedCartRecoveryRouter);
  app.use('/api/ebay-cross-promotion-engine', ebayCrossPromotionEngineRouter);
  app.use('/api/ebay-seller-benchmarking', ebaySellerBenchmarkingRouter);
  app.use('/api/ebay-inventory-transfer-manager', ebayInventoryTransferManagerRouter);
  app.use('/api/ebay-ai-product-description-generator', ebayAiProductDescriptionGeneratorRouter);
  // Phase 401-405
  app.use('/api/ebay-listing-watermark-tool', ebayListingWatermarkToolRouter);
  app.use('/api/ebay-order-batch-processor', ebayOrderBatchProcessorRouter);
  app.use('/api/ebay-keyword-rank-tracker', ebayKeywordRankTrackerRouter);
  app.use('/api/ebay-supplier-order-tracker', ebaySupplierOrderTrackerRouter);
  app.use('/api/ebay-listing-seo-audit', ebayListingSeoAuditRouter);
  // Phase 406-410
  app.use('/api/ebay-store-theme-customizer', ebayStoreThemeCustomizerRouter);
  app.use('/api/ebay-profit-margin-calculator', ebayProfitMarginCalculatorRouter);
  app.use('/api/ebay-listing-rotation-scheduler', ebayListingRotationSchedulerRouter);
  app.use('/api/ebay-customer-feedback-loop', ebayCustomerFeedbackLoopRouter);
  app.use('/api/ebay-smart-inventory-allocator', ebaySmartInventoryAllocatorRouter);
  // Phase 411-415
  app.use('/api/ebay-listing-ab-test-manager', ebayListingAbTestManagerRouter);
  app.use('/api/ebay-returns-dashboard-pro', ebayReturnsDashboardProRouter);
  app.use('/api/ebay-inventory-snapshot-tool', ebayInventorySnapshotToolRouter);
  app.use('/api/ebay-shipping-insurance-manager', ebayShippingInsuranceManagerRouter);
  app.use('/api/ebay-listing-expiry-tracker', ebayListingExpiryTrackerRouter);
  // Phase 416-420
  app.use('/api/ebay-order-consolidation-tool', ebayOrderConsolidationToolRouter);
  app.use('/api/ebay-listing-draft-manager', ebayListingDraftManagerRouter);
  app.use('/api/ebay-seller-goal-tracker', ebaySellerGoalTrackerRouter);
  app.use('/api/ebay-price-comparison-engine', ebayPriceComparisonEngineRouter);
  app.use('/api/ebay-bulk-description-updater', ebayBulkDescriptionUpdaterRouter);
  // Phase 421-425
  app.use('/api/ebay-warehouse-picking-optimizer', ebayWarehousePickingOptimizerRouter);
  app.use('/api/ebay-product-lifecycle-manager', ebayProductLifecycleManagerRouter);
  app.use('/api/ebay-seller-tax-report-generator', ebaySellerTaxReportGeneratorRouter);
  app.use('/api/ebay-listing-quality-scorer-pro', ebayListingQualityScorerProRouter);
  app.use('/api/ebay-multi-account-manager', ebayMultiAccountManagerRouter);
  // Phase 426-430
  app.use('/api/ebay-order-gift-wrapper', ebayOrderGiftWrapperRouter);
  app.use('/api/ebay-inventory-count-scheduler', ebayInventoryCountSchedulerRouter);
  app.use('/api/ebay-seller-onboarding-wizard', ebaySellerOnboardingWizardRouter);
  app.use('/api/ebay-listing-impression-tracker', ebayListingImpressionTrackerRouter);
  app.use('/api/ebay-automated-repricing-bot', ebayAutomatedRepricingBotRouter);
  // Phase 431-435
  app.use('/api/ebay-shipping-zone-manager', ebayShippingZoneManagerRouter);
  app.use('/api/ebay-product-tag-manager', ebayProductTagManagerRouter);
  app.use('/api/ebay-order-risk-scorer', ebayOrderRiskScorerRouter);
  app.use('/api/ebay-listing-freshness-monitor', ebayListingFreshnessMonitorRouter);
  app.use('/api/ebay-carrier-performance-tracker', ebayCarrierPerformanceTrackerRouter);
  // Phase 436-440
  app.use('/api/ebay-inventory-shrinkage-tracker', ebayInventoryShrinkageTrackerRouter);
  app.use('/api/ebay-seller-reputation-guard', ebaySellerReputationGuardRouter);
  app.use('/api/ebay-listing-conversion-optimizer', ebayListingConversionOptimizerRouter);
  app.use('/api/ebay-order-routing-engine', ebayOrderRoutingEngineRouter);
  app.use('/api/ebay-product-review-aggregator', ebayProductReviewAggregatorRouter);
  // Phase 441-445
  app.use('/api/ebay-listing-calendar', ebayListingCalendarRouter);
  app.use('/api/ebay-order-escalation-manager', ebayOrderEscalationManagerRouter);
  app.use('/api/ebay-product-authentication-badge', ebayProductAuthenticationBadgeRouter);
  app.use('/api/ebay-seller-community-hub', ebaySellerCommunityHubRouter);
  app.use('/api/ebay-inventory-reservation-manager', ebayInventoryReservationManagerRouter);
  // Phase 446-450
  app.use('/api/ebay-smart-bundle-creator', ebaySmartBundleCreatorRouter);
  app.use('/api/ebay-listing-health-monitor-pro', ebayListingHealthMonitorProRouter);
  app.use('/api/ebay-order-delivery-tracker', ebayOrderDeliveryTrackerRouter);
  app.use('/api/ebay-product-catalog-enrichment', ebayProductCatalogEnrichmentRouter);
  app.use('/api/ebay-seller-performance-optimizer', ebaySellerPerformanceOptimizerRouter);
  // Phase 451-455
  app.use('/api/ebay-return-label-generator', ebayReturnLabelGeneratorRouter);
  app.use('/api/ebay-competitor-price-alert', ebayCompetitorPriceAlertRouter);
  app.use('/api/ebay-shipping-cost-splitter', ebayShippingCostSplitterRouter);
  app.use('/api/ebay-product-condition-grader', ebayProductConditionGraderRouter);
  app.use('/api/ebay-order-fulfillment-optimizer', ebayOrderFulfillmentOptimizerRouter);
  // Phase 456-460
  app.use('/api/ebay-listing-image-ai-optimizer', ebayListingImageAiOptimizerRouter);
  app.use('/api/ebay-buyer-loyalty-program', ebayBuyerLoyaltyProgramRouter);
  app.use('/api/ebay-inventory-demand-planner', ebayInventoryDemandPlannerRouter);
  app.use('/api/ebay-listing-translation-hub', ebayListingTranslationHubRouter);
  app.use('/api/ebay-seller-financial-dashboard', ebaySellerFinancialDashboardRouter);
  // Phase 461-465
  app.use('/api/ebay-order-cancellation-manager', ebayOrderCancellationManagerRouter);
  app.use('/api/ebay-listing-category-advisor', ebayListingCategoryAdvisorRouter);
  app.use('/api/ebay-seller-payout-tracker', ebaySellerPayoutTrackerRouter);
  app.use('/api/ebay-product-cross-reference-tool', ebayProductCrossReferenceToolRouter);
  app.use('/api/ebay-listing-promotion-scheduler', ebayListingPromotionSchedulerRouter);
}
