import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================================
// IS_INITIAL_DATA → ItemSpecificsField テーブル
// ============================================================
interface InitialFieldData {
  category: string;
  tagJp: string;
  fieldName: string;
  fieldType: string;
  priority: number;
  notes: string;
}

const INITIAL_DATA: InitialFieldData[] = [
  // === Watches ===
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Reference Number', fieldType: 'required', priority: 2, notes: 'モデル番号・型番' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Model', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Type', fieldType: 'required', priority: 4, notes: 'Wristwatch / Pocket Watch' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Case Material', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Band Material', fieldType: 'required', priority: 6, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Department', fieldType: 'required', priority: 7, notes: "Men's / Women's / Unisex" },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Movement', fieldType: 'recommended', priority: 8, notes: 'Mechanical / Automatic / Quartz' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Dial Color', fieldType: 'recommended', priority: 9, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Case Size', fieldType: 'recommended', priority: 10, notes: 'mm単位' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Year Manufactured', fieldType: 'recommended', priority: 11, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Water Resistance', fieldType: 'recommended', priority: 12, notes: '' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 13, notes: '製造国（本社所在国ではない）。フルネーム英語' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'With Papers', fieldType: 'recommended', priority: 14, notes: 'Yes / No' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'With Original Box', fieldType: 'recommended', priority: 15, notes: 'Yes / No' },
  { category: 'Watches', tagJp: '時計,腕時計,ウォッチ,懐中時計', fieldName: 'Display', fieldType: 'recommended', priority: 16, notes: 'Analog / Digital / Analog & Digital' },
  // === Rings ===
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Metal', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Metal Purity', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Main Stone', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Type', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Ring Size', fieldType: 'required', priority: 6, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Cut Grade', fieldType: 'recommended', priority: 7, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Main Stone Color', fieldType: 'recommended', priority: 8, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Main Stone Creation', fieldType: 'recommended', priority: 9, notes: 'Natural / Lab-Created' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Setting Style', fieldType: 'recommended', priority: 10, notes: '' },
  { category: 'Rings', tagJp: 'リング,指輪,リング・指輪', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 11, notes: '' },
  // === Necklaces & Pendants ===
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Metal', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Metal Purity', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Main Stone', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Type', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Chain Length', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Chain Type', fieldType: 'recommended', priority: 7, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Setting Style', fieldType: 'recommended', priority: 8, notes: '' },
  { category: 'Necklaces & Pendants', tagJp: 'ネックレス,ペンダント,チェーン', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 9, notes: '' },
  // === Bracelets ===
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Metal', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Metal Purity', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Main Stone', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Type', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Length', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Closure', fieldType: 'recommended', priority: 7, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Setting Style', fieldType: 'recommended', priority: 8, notes: '' },
  { category: 'Bracelets', tagJp: 'ブレスレット,バングル', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 9, notes: '' },
  // === Earrings ===
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Metal', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Metal Purity', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Main Stone', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Type', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Fastening', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Setting Style', fieldType: 'recommended', priority: 7, notes: '' },
  { category: 'Earrings', tagJp: 'ピアス,イヤリング', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 8, notes: '' },
  // === Handbags ===
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Exterior Color', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Exterior Material', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Style', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Department', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Pattern', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Handle/Strap Material', fieldType: 'recommended', priority: 7, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Lining Material', fieldType: 'recommended', priority: 8, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Hardware Color', fieldType: 'recommended', priority: 9, notes: '' },
  { category: 'Handbags', tagJp: 'バッグ,ハンドバッグ,ショルダーバッグ,トートバッグ,リュック,ボストンバッグ,クラッチバッグ', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 10, notes: '' },
  // === Clothing ===
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Size', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Size Type', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Color', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Department', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Type', fieldType: 'required', priority: 6, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Style', fieldType: 'required', priority: 7, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Material', fieldType: 'recommended', priority: 8, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Pattern', fieldType: 'recommended', priority: 9, notes: '' },
  { category: 'Clothing', tagJp: '衣類,服,トップス,ボトムス,ジャケット,コート,ドレス,スカート,パンツ', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 10, notes: '' },
  // === Cameras ===
  { category: 'Cameras', tagJp: 'カメラ,デジカメ,一眼レフ,ミラーレス', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Cameras', tagJp: 'カメラ,デジカメ,一眼レフ,ミラーレス', fieldName: 'Model', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Cameras', tagJp: 'カメラ,デジカメ,一眼レフ,ミラーレス', fieldName: 'Type', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Cameras', tagJp: 'カメラ,デジカメ,一眼レフ,ミラーレス', fieldName: 'Color', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Cameras', tagJp: 'カメラ,デジカメ,一眼レフ,ミラーレス', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 5, notes: '' },
  // === Electronics ===
  { category: 'Electronics', tagJp: '電子機器,家電,オーディオ,ヘッドホン,イヤホン,スピーカー', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Electronics', tagJp: '電子機器,家電,オーディオ,ヘッドホン,イヤホン,スピーカー', fieldName: 'Model', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Electronics', tagJp: '電子機器,家電,オーディオ,ヘッドホン,イヤホン,スピーカー', fieldName: 'Type', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Electronics', tagJp: '電子機器,家電,オーディオ,ヘッドホン,イヤホン,スピーカー', fieldName: 'Color', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Electronics', tagJp: '電子機器,家電,オーディオ,ヘッドホン,イヤホン,スピーカー', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 5, notes: '' },
  // === Trading Cards ===
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Game', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Set', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Character', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Card Name', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Language', fieldType: 'recommended', priority: 5, notes: '' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Graded', fieldType: 'recommended', priority: 6, notes: 'Yes / No' },
  { category: 'Trading Cards', tagJp: 'トレカ,カード,トレーディングカード,ポケカ,遊戯王,MTG', fieldName: 'Rarity', fieldType: 'recommended', priority: 7, notes: '' },
  // === Shoes ===
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'US Shoe Size', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Color', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Type', fieldType: 'required', priority: 4, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Department', fieldType: 'required', priority: 5, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Material', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Shoes', tagJp: '靴,シューズ,スニーカー,ブーツ,サンダル,パンプス,ローファー', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 7, notes: '' },
  // === Collectibles ===
  { category: 'Collectibles', tagJp: 'コレクティブル,フィギュア,アンティーク,ヴィンテージ,骨董品,人形', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Collectibles', tagJp: 'コレクティブル,フィギュア,アンティーク,ヴィンテージ,骨董品,人形', fieldName: 'Type', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Collectibles', tagJp: 'コレクティブル,フィギュア,アンティーク,ヴィンテージ,骨董品,人形', fieldName: 'Theme', fieldType: 'recommended', priority: 3, notes: '' },
  { category: 'Collectibles', tagJp: 'コレクティブル,フィギュア,アンティーク,ヴィンテージ,骨董品,人形', fieldName: 'Material', fieldType: 'recommended', priority: 4, notes: '' },
  { category: 'Collectibles', tagJp: 'コレクティブル,フィギュア,アンティーク,ヴィンテージ,骨董品,人形', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 5, notes: '' },
  // === Watch Parts ===
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Brand', fieldType: 'required', priority: 1, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Part Type', fieldType: 'required', priority: 2, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Material', fieldType: 'required', priority: 3, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Compatible Model', fieldType: 'recommended', priority: 4, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Size', fieldType: 'recommended', priority: 5, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Color', fieldType: 'recommended', priority: 6, notes: '' },
  { category: 'Watch Parts', tagJp: 'ウォッチパーツ,時計パーツ,時計部品', fieldName: 'Country of Origin', fieldType: 'recommended', priority: 7, notes: '' },
];

// ============================================================
// IS_BRAND_DICT → Brand テーブル
// データが大量（約540件）なので、Config_IS.gsから全て転記する
// ============================================================
interface BrandData {
  name: string;
  jpNames: string[];
  country: string;
  parentBrand?: string;
  categories?: string[];
  isMaterial?: boolean;
}

// 注意: このデータは ~/Desktop/ツール開発/一括シートApps_v3/ItemSpecifics/Config_IS.gs の
// IS_BRAND_DICT 配列（246行目〜786行目）から全て転記したものを貼り付けてください。
// 変換ルール: jp_names → jpNames, parent_brand → parentBrand, is_material → isMaterial, category → categories
// 例:
// { name: 'Rolex', jpNames: ['ロレックス', 'ROLEX'], country: 'Switzerland' },
// { name: 'Submariner', jpNames: ['サブマリーナ', 'SUBMARINER'], country: 'Switzerland', parentBrand: 'Rolex', categories: ['Watches'] },
const BRAND_DATA: BrandData[] = [
  { name: "Accutron", jpNames: ["アキュトロン","ACCUTRON"], country: "USA", parentBrand: "Bulova", categories: ["Watches"] },
  { name: "Air-King", jpNames: ["エアキング","AIR-KING","AIR KING"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Aquanaut", jpNames: ["アクアノート","AQUANAUT"], country: "Switzerland", parentBrand: "Patek Philippe", categories: ["Watches"] },
  { name: "Aquaracer", jpNames: ["アクアレーサー","AQUARACER"], country: "Switzerland", parentBrand: "TAG Heuer", categories: ["Watches"] },
  { name: "Attesa", jpNames: ["アテッサ","ATTESA"], country: "Japan", parentBrand: "Citizen", categories: ["Watches"] },
  { name: "Audemars Piguet", jpNames: ["オーデマピゲ","AUDEMARS PIGUET"], country: "Switzerland" },
  { name: "Avenger", jpNames: ["アベンジャー","AVENGER"], country: "Switzerland", parentBrand: "Breitling", categories: ["Watches"] },
  { name: "Baby-G", jpNames: ["ベビーG","BABY-G","BABYG","BABY G"], country: "Japan", parentBrand: "Casio", categories: ["Watches"] },
  { name: "Ball Watch", jpNames: ["ボールウォッチ","BALL WATCH"], country: "USA" },
  { name: "Ballon Bleu", jpNames: ["バロンブルー","BALLON BLEU"], country: "France", parentBrand: "Cartier", categories: ["Watches"] },
  { name: "Bambino", jpNames: ["バンビーノ","BAMBINO"], country: "Japan", parentBrand: "Orient", categories: ["Watches"] },
  { name: "Banks", jpNames: ["バンクス","BANKS"], country: "USA", parentBrand: "Nixon", categories: ["Watches"] },
  { name: "Baume & Mercier", jpNames: ["ボーム&メルシエ","BAUME & MERCIER","BAUME&MERCIER"], country: "Switzerland" },
  { name: "Bell & Ross", jpNames: ["ベル&ロス","BELL & ROSS","BELL&ROSS"], country: "France" },
  { name: "Big Bang", jpNames: ["ビッグバン","BIG BANG"], country: "Switzerland", parentBrand: "Hublot", categories: ["Watches"] },
  { name: "Black Bay", jpNames: ["ブラックベイ","BLACK BAY"], country: "Switzerland", parentBrand: "Tudor", categories: ["Watches"] },
  { name: "Blancpain", jpNames: ["ブランパン","BLANCPAIN"], country: "Switzerland" },
  { name: "Breguet", jpNames: ["ブレゲ","BREGUET"], country: "Switzerland" },
  { name: "Breitling", jpNames: ["ブライトリング","BREITLING"], country: "Switzerland" },
  { name: "Bremont", jpNames: ["ブレモン","BREMONT"], country: "UK" },
  { name: "Bulova", jpNames: ["ブローバ","BULOVA"], country: "USA" },
  { name: "Buren", jpNames: ["ビューレン","BUREN"], country: "Switzerland" },
  { name: "Calatrava", jpNames: ["カラトラバ","CALATRAVA"], country: "Switzerland", parentBrand: "Patek Philippe", categories: ["Watches"] },
  { name: "Campanola", jpNames: ["カンパノラ","CAMPANOLA"], country: "Japan" },
  { name: "Captain Cook", jpNames: ["キャプテンクック","CAPTAIN COOK"], country: "Switzerland", parentBrand: "Rado", categories: ["Watches"] },
  { name: "Carrera", jpNames: ["カレラ","CARRERA"], country: "Switzerland", parentBrand: "TAG Heuer", categories: ["Watches"] },
  { name: "Cartier", jpNames: ["カルティエ","CARTIER"], country: "France" },
  { name: "Casio", jpNames: ["カシオ","CASIO"], country: "Japan" },
  { name: "Chronomat", jpNames: ["クロノマット","CHRONOMAT"], country: "Switzerland", parentBrand: "Breitling", categories: ["Watches"] },
  { name: "Classic Fusion", jpNames: ["クラシックフュージョン","CLASSIC FUSION"], country: "Switzerland", parentBrand: "Hublot", categories: ["Watches"] },
  { name: "Citizen", jpNames: ["シチズン","CITIZEN"], country: "Japan" },
  { name: "Conquest", jpNames: ["コンクエスト","CONQUEST"], country: "Switzerland", parentBrand: "Longines", categories: ["Watches"] },
  { name: "Constellation", jpNames: ["コンステレーション","CONSTELLATION"], country: "Switzerland", parentBrand: "Omega", categories: ["Watches"] },
  { name: "Credor", jpNames: ["クレドール","CREDOR"], country: "Japan" },
  { name: "Daniel Wellington", jpNames: ["ダニエルウェリントン","DANIEL WELLINGTON","DW"], country: "Sweden" },
  { name: "Datejust", jpNames: ["デイトジャスト","DATEJUST"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Day-Date", jpNames: ["デイデイト","DAY-DATE"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Daytona", jpNames: ["デイトナ","DAYTONA"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "De Ville", jpNames: ["デ・ヴィル","デビル","DE VILLE"], country: "Switzerland", parentBrand: "Omega", categories: ["Watches"] },
  { name: "Descent", jpNames: ["ディセント","DESCENT"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "DiaStar", jpNames: ["ダイヤスター","DIASTAR"], country: "Switzerland", parentBrand: "Rado", categories: ["Watches"] },
  { name: "Edifice", jpNames: ["エディフィス","EDIFICE"], country: "Japan", parentBrand: "Casio", categories: ["Watches"] },
  { name: "Exceed", jpNames: ["エクシード","EXCEED"], country: "Japan", parentBrand: "Citizen", categories: ["Watches"] },
  { name: "Explorer", jpNames: ["エクスプローラー","EXPLORER"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Fenix", jpNames: ["フェニックス","FENIX"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "Ferrari", jpNames: ["フェラーリ","FERRARI"], country: "Italy", categories: ["Watches"] },
  { name: "Florence", jpNames: ["フローレンス","FLORENCE"], country: "Switzerland", parentBrand: "Rado", categories: ["Watches"] },
  { name: "ForeAthlete", jpNames: ["フォアアスリート","FOREATHLETE"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "Forerunner", jpNames: ["フォアランナー","FORERUNNER"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "Formula 1", jpNames: ["フォーミュラ1","FORMULA 1"], country: "Switzerland", parentBrand: "TAG Heuer", categories: ["Watches"] },
  { name: "Frederique Constant", jpNames: ["フレデリックコンスタント","FREDERIQUE CONSTANT"], country: "Switzerland" },
  { name: "Garmin", jpNames: ["ガーミン","GARMIN"], country: "USA" },
  { name: "GC Watches", jpNames: ["ジーシーウォッチ","GC WATCHES","GC","GUESS COLLECTION"], country: "Switzerland" },
  { name: "Gentleman", jpNames: ["ジェントルマン","GENTLEMAN"], country: "Switzerland", parentBrand: "Tissot", categories: ["Watches"] },
  { name: "Girard-Perregaux", jpNames: ["ジラールペルゴ","GIRARD-PERREGAUX","GIRARD PERREGAUX"], country: "Switzerland" },
  { name: "Glashütte Original", jpNames: ["グラスヒュッテオリジナル","GLASHUTTE ORIGINAL"], country: "Germany" },
  { name: "G-Shock", jpNames: ["Gショック","G-SHOCK","GSHOCK","G SHOCK"], country: "Japan", parentBrand: "Casio" },
  { name: "GMT-Master", jpNames: ["GMTマスター","GMT-MASTER","GMT MASTER"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Golden Horse", jpNames: ["ゴールデンホース","GOLDEN HORSE"], country: "Switzerland", parentBrand: "Rado", categories: ["Watches"] },
  { name: "Grand Seiko", jpNames: ["グランドセイコー","GRAND SEIKO"], country: "Japan", parentBrand: "Seiko" },
  { name: "Hamilton", jpNames: ["ハミルトン","HAMILTON"], country: "USA" },
  { name: "Hublot", jpNames: ["ウブロ","HUBLOT"], country: "Switzerland" },
  { name: "HydroConquest", jpNames: ["ハイドロコンクエスト","HYDROCONQUEST"], country: "Switzerland", parentBrand: "Longines", categories: ["Watches"] },
  { name: "Independent", jpNames: ["インディペンデント","INDEPENDENT"], country: "Japan" },
  { name: "Ingenieur", jpNames: ["インヂュニア","INGENIEUR"], country: "Switzerland", parentBrand: "IWC", categories: ["Watches"] },
  { name: "Instinct", jpNames: ["インスティンクト","INSTINCT"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "IWC", jpNames: ["IWC"], country: "Switzerland" },
  { name: "Jaeger-LeCoultre", jpNames: ["ジャガールクルト","JAEGER-LECOULTRE","JAEGER LECOULTRE"], country: "Switzerland" },
  { name: "Jazzmaster", jpNames: ["ジャズマスター","JAZZMASTER"], country: "USA", parentBrand: "Hamilton", categories: ["Watches"] },
  { name: "Junghans", jpNames: ["ユンハンス","JUNGHANS"], country: "Germany" },
  { name: "Kamasu", jpNames: ["カマス","KAMASU"], country: "Japan", parentBrand: "Orient", categories: ["Watches"] },
  { name: "Khaki Aviation", jpNames: ["カーキアビエーション","KHAKI AVIATION"], country: "USA", parentBrand: "Hamilton", categories: ["Watches"] },
  { name: "Khaki Field", jpNames: ["カーキフィールド","KHAKI FIELD"], country: "USA", parentBrand: "Hamilton", categories: ["Watches"] },
  { name: "King Seiko", jpNames: ["キングセイコー","KING SEIKO"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Knot", jpNames: ["ノット","KNOT"], country: "Japan" },
  { name: "Kurono Tokyo", jpNames: ["クロノトウキョウ","KURONO TOKYO"], country: "Japan" },
  { name: "Le Locle", jpNames: ["ル・ロックル","LE LOCLE"], country: "Switzerland", parentBrand: "Tissot", categories: ["Watches"] },
  { name: "Legend Diver", jpNames: ["レジェンドダイバー","LEGEND DIVER"], country: "Switzerland", parentBrand: "Longines", categories: ["Watches"] },
  { name: "Longines", jpNames: ["ロンジン","LONGINES"], country: "Switzerland" },
  { name: "Luminor", jpNames: ["ルミノール","LUMINOR"], country: "Italy", parentBrand: "Panerai", categories: ["Watches"] },
  { name: "Luminox", jpNames: ["ルミノックス","LUMINOX"], country: "USA" },
  { name: "Mako", jpNames: ["マコ","MAKO"], country: "Japan", parentBrand: "Orient", categories: ["Watches"] },
  { name: "Marine Star", jpNames: ["マリンスター","MARINE STAR"], country: "USA", parentBrand: "Bulova", categories: ["Watches"] },
  { name: "Maurice Lacroix", jpNames: ["モーリスラクロア","MAURICE LACROIX"], country: "Switzerland" },
  { name: "Minase", jpNames: ["ミナセ","MINASE"], country: "Japan" },
  { name: "Monaco", jpNames: ["モナコ","MONACO"], country: "Switzerland", parentBrand: "TAG Heuer", categories: ["Watches"] },
  { name: "Nautilus", jpNames: ["ノーチラス","NAUTILUS"], country: "Switzerland", parentBrand: "Patek Philippe", categories: ["Watches"] },
  { name: "Navitimer", jpNames: ["ナビタイマー","NAVITIMER"], country: "Switzerland", parentBrand: "Breitling", categories: ["Watches"] },
  { name: "Nixon", jpNames: ["ニクソン","NIXON"], country: "USA" },
  { name: "Nomos", jpNames: ["ノモス","NOMOS"], country: "Germany" },
  { name: "Oceanus", jpNames: ["オシアナス","OCEANUS"], country: "Japan", parentBrand: "Casio", categories: ["Watches"] },
  { name: "Omega", jpNames: ["オメガ","OMEGA"], country: "Switzerland" },
  { name: "Orient", jpNames: ["オリエント","ORIENT"], country: "Japan" },
  { name: "Orient Star", jpNames: ["オリエントスター","ORIENT STAR"], country: "Japan", parentBrand: "Orient" },
  { name: "Oris", jpNames: ["オリス","ORIS"], country: "Switzerland" },
  { name: "Oyster Perpetual", jpNames: ["オイスターパーペチュアル","OYSTER PERPETUAL"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Panerai", jpNames: ["パネライ","PANERAI"], country: "Italy" },
  { name: "Panthere", jpNames: ["パンテール","PANTHERE"], country: "France", parentBrand: "Cartier", categories: ["Watches"] },
  { name: "Pasha", jpNames: ["パシャ","PASHA"], country: "France", parentBrand: "Cartier", categories: ["Watches"] },
  { name: "Patek Philippe", jpNames: ["パテックフィリップ","PATEK PHILIPPE"], country: "Switzerland" },
  { name: "Pelagos", jpNames: ["ペラゴス","PELAGOS"], country: "Switzerland", parentBrand: "Tudor", categories: ["Watches"] },
  { name: "Philippe Charriol", jpNames: ["フィリップシャリオール","シャリオール","PHILIPPE CHARRIOL","CHARRIOL"], country: "Switzerland" },
  { name: "Piaget", jpNames: ["ピアジェ","PIAGET"], country: "Switzerland" },
  { name: "Pierre Lannier", jpNames: ["ピエールラニエ","PIERRE LANNIER"], country: "France" },
  { name: "Portofino", jpNames: ["ポートフィノ","PORTOFINO"], country: "Switzerland", parentBrand: "IWC", categories: ["Watches"] },
  { name: "Portugieser", jpNames: ["ポルトギーゼ","PORTUGIESER"], country: "Switzerland", parentBrand: "IWC", categories: ["Watches"] },
  { name: "Precisionist", jpNames: ["プレシジョニスト","PRECISIONIST"], country: "USA", parentBrand: "Bulova", categories: ["Watches"] },
  { name: "PRX", jpNames: ["ピーアールエックス","PRX"], country: "Switzerland", parentBrand: "Tissot", categories: ["Watches"] },
  { name: "Pro Trek", jpNames: ["プロトレック","PRO TREK","PROTREK"], country: "Japan", parentBrand: "Casio", categories: ["Watches"] },
  { name: "Promaster", jpNames: ["プロマスター","PROMASTER"], country: "Japan", parentBrand: "Citizen", categories: ["Watches"] },
  { name: "Radiomir", jpNames: ["ラジオミール","RADIOMIR"], country: "Italy", parentBrand: "Panerai", categories: ["Watches"] },
  { name: "Rado", jpNames: ["ラドー","RADO"], country: "Switzerland" },
  { name: "Rolex", jpNames: ["ロレックス","ROLEX"], country: "Switzerland" },
  { name: "Rolex Custom", jpNames: ["ロレックスカスタム","ROLEX CUSTOM"], country: "Switzerland" },
  { name: "Royal Oak", jpNames: ["ロイヤルオーク","ROYAL OAK"], country: "Switzerland", parentBrand: "Audemars Piguet", categories: ["Watches"] },
  { name: "Royal Oak Offshore", jpNames: ["ロイヤルオークオフショア","ROYAL OAK OFFSHORE"], country: "Switzerland", parentBrand: "Audemars Piguet", categories: ["Watches"] },
  { name: "Santos", jpNames: ["サントス","SANTOS"], country: "France", parentBrand: "Cartier", categories: ["Watches"] },
  { name: "Sea-Dweller", jpNames: ["シードゥエラー","SEA-DWELLER","SEA DWELLER"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Seamaster", jpNames: ["シーマスター","SEAMASTER"], country: "Switzerland", parentBrand: "Omega", categories: ["Watches"] },
  { name: "Seastar", jpNames: ["シースター","SEASTAR"], country: "Switzerland", parentBrand: "Tissot", categories: ["Watches"] },
  { name: "Seiko", jpNames: ["セイコー","SEIKO"], country: "Japan" },
  { name: "Seiko 5", jpNames: ["セイコー5","SEIKO 5","セイコーファイブ"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Astron", jpNames: ["アストロン","ASTRON"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Brightz", jpNames: ["ブライツ","BRIGHTZ"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Dolce", jpNames: ["ドルチェ","DOLCE"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Lukia", jpNames: ["ルキア","LUKIA"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Presage", jpNames: ["プレザージュ","PRESAGE"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seiko Prospex", jpNames: ["プロスペックス","PROSPEX"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Seikomatic", jpNames: ["セイコーマチック","SEIKOMATIC"], country: "Japan" },
  { name: "Seikosha", jpNames: ["精工舎","SEIKOSHA","SEIKOSYA"], country: "Japan" },
  { name: "Shinola", jpNames: ["シノラ","SHINOLA"], country: "USA" },
  { name: "Speedmaster", jpNames: ["スピードマスター","SPEEDMASTER"], country: "Switzerland", parentBrand: "Omega", categories: ["Watches"] },
  { name: "Sportura", jpNames: ["スポーチュラ","SPORTURA"], country: "Japan", parentBrand: "Seiko", categories: ["Watches"] },
  { name: "Submariner", jpNames: ["サブマリーナ","SUBMARINER"], country: "Switzerland", parentBrand: "Rolex", categories: ["Watches"] },
  { name: "Submersible", jpNames: ["サブマーシブル","SUBMERSIBLE"], country: "Italy", parentBrand: "Panerai", categories: ["Watches"] },
  { name: "Superocean", jpNames: ["スーパーオーシャン","SUPEROCEAN"], country: "Switzerland", parentBrand: "Breitling", categories: ["Watches"] },
  { name: "Swatch", jpNames: ["スウォッチ","SWATCH"], country: "Switzerland" },
  { name: "TAG Heuer", jpNames: ["タグホイヤー","TAG HEUER"], country: "Switzerland" },
  { name: "Tank", jpNames: ["タンク","TANK"], country: "France", parentBrand: "Cartier", categories: ["Watches"] },
  { name: "The Citizen", jpNames: ["ザ・シチズン","THE CITIZEN"], country: "Japan", parentBrand: "Citizen", categories: ["Watches"] },
  { name: "Tide", jpNames: ["タイド","TIDE"], country: "USA", parentBrand: "Nixon", categories: ["Watches"] },
  { name: "Tissot", jpNames: ["ティソ","TISSOT"], country: "Switzerland" },
  { name: "Tudor", jpNames: ["チュードル","チューダー","TUDOR"], country: "Switzerland" },
  { name: "Ulysse Nardin", jpNames: ["ユリスナルダン","ULYSSE NARDIN"], country: "Switzerland" },
  { name: "Vacheron Constantin", jpNames: ["ヴァシュロンコンスタンタン","VACHERON CONSTANTIN"], country: "Switzerland" },
  { name: "Ventura", jpNames: ["ベンチュラ","VENTURA"], country: "USA", parentBrand: "Hamilton", categories: ["Watches"] },
  { name: "Venu", jpNames: ["ヴェニュー","VENU"], country: "USA", parentBrand: "Garmin", categories: ["Watches"] },
  { name: "Wenger", jpNames: ["ウェンガー","WENGER"], country: "Switzerland" },
  { name: "xC", jpNames: ["クロスシー","XC"], country: "Japan", parentBrand: "Citizen", categories: ["Watches"] },
  { name: "Zenith", jpNames: ["ゼニス","ZENITH"], country: "Switzerland" },
  { name: "Zeppelin", jpNames: ["ツェッペリン","ZEPPELIN"], country: "Germany" },
  { name: "U-Boat", jpNames: ["ユーボート","U BOAT","UBOAT"], country: "Italy" },
  { name: "GaGa Milano", jpNames: ["ガガミラノ","GAGA MILANO","GAGA","ガガ ミラノ"], country: "Italy" },
  { name: "4℃", jpNames: ["ヨンドシー","4℃"], country: "Japan" },
  { name: "Agete", jpNames: ["アガット","AGETE"], country: "Japan" },
  { name: "Ahkah", jpNames: ["アーカー","AHKAH"], country: "Japan" },
  { name: "Alexandre de Paris", jpNames: ["アレクサンドルドゥパリ","アレクサンドル ドゥ パリ","ALEXANDRE DE PARIS"], country: "France" },
  { name: "Bill Wall Leather", jpNames: ["ビルウォールレザー","BILL WALL LEATHER"], country: "USA" },
  { name: "Boucheron", jpNames: ["ブシュロン","BOUCHERON"], country: "France" },
  { name: "Bulgari", jpNames: ["ブルガリ","BVLGARI"], country: "Italy" },
  { name: "Bvlgari", jpNames: ["ブルガリ","BVLGARI"], country: "Italy" },
  { name: "Chaumet", jpNames: ["ショーメ","CHAUMET"], country: "France" },
  { name: "Chopard", jpNames: ["ショパール","CHOPARD"], country: "Switzerland" },
  { name: "Chrome Hearts", jpNames: ["クロムハーツ","CHROME HEARTS"], country: "USA" },
  { name: "Cody Sanderson", jpNames: ["コディサンダーソン","CODY SANDERSON"], country: "USA" },
  { name: "Damiani", jpNames: ["ダミアーニ","DAMIANI"], country: "Italy" },
  { name: "David Andersen", jpNames: ["デヴィッドアンデルセン","DAVID ANDERSEN","D.ANDERSEN"], country: "Norway" },
  { name: "David Yurman", jpNames: ["デイビット・ヤーマン","DAVID YURMAN"], country: "USA" },
  { name: "Emporio Armani", jpNames: ["エンポリオアルマーニ","EMPORIO ARMANI"], country: "Italy" },
  { name: "Ete", jpNames: ["エテ","ETE"], country: "Japan" },
  { name: "Etro", jpNames: ["エトロ","ETRO"], country: "Italy" },
  { name: "Fred", jpNames: ["フレッド","FRED"], country: "France" },
  { name: "Gucci", jpNames: ["グッチ","GUCCI"], country: "Italy" },
  { name: "Hans Hansen", jpNames: ["ハンスハンセン","HANS HANSEN"], country: "Denmark" },
  { name: "Harry Winston", jpNames: ["ハリー・ウィンストン","HARRY WINSTON"], country: "USA" },
  { name: "Hermes", jpNames: ["エルメス","HERMES"], country: "France" },
  { name: "Justin Davis", jpNames: ["ジャスティン・デイビス","JUSTIN DAVIS"], country: "USA" },
  { name: "Louis Faglin", jpNames: ["ルイファグラン","LOUIS FAGLIN"], country: "France" },
  { name: "Max Mara", jpNames: ["マックスマーラ","MAX MARA"], country: "Italy" },
  { name: "Mikimoto", jpNames: ["ミキモト","MIKIMOTO"], country: "Japan" },
  { name: "Pandora", jpNames: ["パンドラ","PANDORA"], country: "Denmark" },
  { name: "Paul Smith", jpNames: ["ポールスミス","ポール・スミス","PAUL SMITH"], country: "UK" },
  { name: "Swarovski", jpNames: ["スワロフスキー","SWAROVSKI"], country: "Austria", isMaterial: true },
  { name: "Tasaki", jpNames: ["タサキ","TASAKI"], country: "Japan" },
  { name: "Tateossian", jpNames: ["タテオシアン","TATEOSSIAN"], country: "UK" },
  { name: "Tiffany & Co.", jpNames: ["ティファニー","TIFFANY & CO.","TIFFANY","TIFFANY&CO","Tiffany"], country: "USA" },
  { name: "Van Cleef & Arpels", jpNames: ["ヴァン クリーフ＆アーペル","VAN CLEEF & ARPELS","VAN CLEEF","VANCLEEF&ARPELS"], country: "France" },
  { name: "Vivienne Westwood", jpNames: ["ヴィヴィアン・ウエストウッド","VIVIENNE WESTWOOD"], country: "UK" },
  { name: "Trollbeads", jpNames: ["トロールビーズ","TROLLBEADS"], country: "Denmark" },
  { name: "Yves Saint Laurent", jpNames: ["イヴサンローラン","イブサンローラン","YVES SAINT LAURENT","YSL"], country: "France" },
  { name: "Maison Margiela", jpNames: ["メゾンマルジェラ","マルジェラ","MAISON MARGIELA","MARGIELA","メゾン マルジェラ"], country: "Italy" },
  { name: "CINER", jpNames: ["シネール","CINER"], country: "USA" },
  { name: "Anello", jpNames: ["アネロ","ANELLO"], country: "Japan" },
  { name: "BRIEFING", jpNames: ["ブリーフィング","BRIEFING"], country: "Japan" },
  { name: "Balenciaga", jpNames: ["バレンシアガ","BALENCIAGA"], country: "France" },
  { name: "Bottega Veneta", jpNames: ["ボッテガ・ヴェネタ","BOTTEGA VENETA"], country: "Italy" },
  { name: "Burberry", jpNames: ["バーバリー","BURBERRY"], country: "UK" },
  { name: "Celine", jpNames: ["セリーヌ","CELINE"], country: "France" },
  { name: "Chanel", jpNames: ["シャネル","CHANEL"], country: "France" },
  { name: "Coach", jpNames: ["コーチ","COACH"], country: "USA" },
  { name: "Dior", jpNames: ["ディオール","DIOR"], country: "France" },
  { name: "Fendi", jpNames: ["フェンディ","FENDI"], country: "Italy" },
  { name: "Goyard", jpNames: ["ゴヤール","GOYARD"], country: "France" },
  { name: "Hunting World", jpNames: ["ハンティングワールド","HUNTING WORLD"], country: "USA" },
  { name: "Loewe", jpNames: ["ロエベ","LOEWE"], country: "Spain" },
  { name: "Louis Vuitton", jpNames: ["ルイ・ヴィトン","LOUIS VUITTON"], country: "France" },
  { name: "Porter", jpNames: ["ポーター","PORTER"], country: "Japan" },
  { name: "Prada", jpNames: ["プラダ","PRADA"], country: "Italy" },
  { name: "Saint Laurent", jpNames: ["サンローラン","SAINT LAURENT"], country: "France" },
  { name: "A Bathing Ape", jpNames: ["ベイプ","BAPE","A BATHING APE","アベイシングエイプ"], country: "Japan" },
  { name: "Agnes b.", jpNames: ["アニエスベー","AGNES B"], country: "France" },
  { name: "Alden", jpNames: ["オールデン","ALDEN"], country: "USA" },
  { name: "Alexander Wang", jpNames: ["アレキサンダーワン","ALEXANDER WANG"], country: "USA" },
  { name: "Anna Sui", jpNames: ["アナスイ","ANNA SUI"], country: "USA" },
  { name: "Aniplex", jpNames: ["アニプレックス","ANIPLEX"], country: "Japan" },
  { name: "BAPE", jpNames: ["ア・ベイシング・エイプ","BAPE"], country: "Japan" },
  { name: "Bally", jpNames: ["バリー","BALLY"], country: "Switzerland" },
  { name: "Bang & Olufsen", jpNames: ["バング&オルフセン","BANG & OLUFSEN","B&O","BANG&OLUFSEN"], country: "Denmark" },
  { name: "Beams", jpNames: ["ビームス","BEAMS"], country: "Japan" },
  { name: "Bloody Mary", jpNames: ["ブラッディマリー","BLOODY MARY"], country: "Japan" },
  { name: "Brooks Brothers", jpNames: ["ブルックスブラザーズ","BROOKS BROTHERS"], country: "USA" },
  { name: "Canada Goose", jpNames: ["カナダグース","CANADA GOOSE"], country: "Canada" },
  { name: "Carhartt", jpNames: ["カーハート","CARHARTT"], country: "USA" },
  { name: "Champion", jpNames: ["チャンピオン","CHAMPION"], country: "USA" },
  { name: "Chloe", jpNames: ["クロエ","CHLOE"], country: "France" },
  { name: "Comme des Garcons", jpNames: ["コムデギャルソン","COMME DES GARCONS"], country: "Japan" },
  { name: "Comme des Garcons Play", jpNames: ["プレイ・コムデギャルソン","PLAY COMME DES GARCONS"], country: "Japan" },
  { name: "Diesel", jpNames: ["ディーゼル","DIESEL"], country: "Italy" },
  { name: "Dolce Gabbana", jpNames: ["ドルチェ&ガッバーナ","DOLCE GABBANA"], country: "Italy" },
  { name: "Dunhill", jpNames: ["ダンヒル","DUNHILL"], country: "UK" },
  { name: "Evisu", jpNames: ["エヴィス","EVISU"], country: "Japan" },
  { name: "Feiler", jpNames: ["フェイラー","FEILER"], country: "Germany" },
  { name: "First Arrow's", jpNames: ["ファーストアローズ","FIRST ARROW'S"], country: "Japan" },
  { name: "Fragment", jpNames: ["フラグメント","FRAGMENT"], country: "Japan" },
  { name: "Fukagawa Seiji", jpNames: ["深川製磁","FUKAGAWA SEIJI"], country: "Japan" },
  { name: "Furla", jpNames: ["フルラ","FURLA"], country: "Italy" },
  { name: "Furyu", jpNames: ["フリュー","FURYU"], country: "Japan" },
  { name: "Gaboratory", jpNames: ["ガボラトリー","GABORATORY"], country: "USA" },
  { name: "Gen-emon", jpNames: ["源右衛門","GEN-EMON","GENEMON"], country: "Japan" },
  { name: "Georg Jensen", jpNames: ["ジョージ・ジェンセン","GEORG JENSEN"], country: "Denmark" },
  { name: "Giant", jpNames: ["ジャイアント","GIANT"], country: "Taiwan" },
  { name: "Gibson", jpNames: ["ギブソン","GIBSON"], country: "USA" },
  { name: "Ginza Tanaka", jpNames: ["ギンザタナカ","GINZA TANAKA"], country: "Japan" },
  { name: "Givenchy", jpNames: ["ジバンシィ","GIVENCHY"], country: "France" },
  { name: "Goldwin", jpNames: ["ゴールドウイン","GOLDWIN"], country: "Japan" },
  { name: "Goro's", jpNames: ["ゴローズ","GORO'S"], country: "Japan" },
  { name: "Graff", jpNames: ["グラフ","GRAFF"], country: "UK" },
  { name: "Greco", jpNames: ["グレコ","GRECO"], country: "Japan" },
  { name: "Gregory", jpNames: ["グレゴリー","GREGORY"], country: "USA" },
  { name: "Hanae Mori", jpNames: ["ハナエモリ","森英恵","HANAE MORI"], country: "Japan" },
  { name: "Head", jpNames: ["ヘッド","HEAD"], country: "Austria" },
  { name: "Herend", jpNames: ["ヘレンド","HEREND"], country: "Hungary" },
  { name: "Human Made", jpNames: ["ヒューマンメイド","HUMAN MADE"], country: "Japan" },
  { name: "Hysteric Glamour", jpNames: ["ヒステリックグラマー","HYSTERIC GLAMOUR"], country: "Japan" },
  { name: "Ichiban Kuji", jpNames: ["一番くじ","ICHIBAN KUJI"], country: "Japan" },
  { name: "Imaemon", jpNames: ["今右衛門","IMAEMON"], country: "Japan" },
  { name: "Issey Miyake", jpNames: ["イッセイミヤケ","ISSEY MIYAKE"], country: "Japan" },
  { name: "Jimmy Choo", jpNames: ["ジミーチュウ","JIMMY CHOO"], country: "UK" },
  { name: "Kadokawa", jpNames: ["KADOKAWA"], country: "Japan" },
  { name: "Kapital", jpNames: ["キャピタル","KAPITAL"], country: "Japan" },
  { name: "Kate Spade", jpNames: ["ケイト・スペード","KATE SPADE"], country: "USA" },
  { name: "Kenwood", jpNames: ["ケンウッド","KENWOOD"], country: "Japan" },
  { name: "Kenzo", jpNames: ["ケンゾー","KENZO"], country: "France" },
  { name: "Kiyomizu", jpNames: ["清水焼","KIYOMIZU"], country: "Japan" },
  { name: "Konica", jpNames: ["コニカ","KONICA"], country: "Japan" },
  { name: "Koransha", jpNames: ["香蘭社","KORANSHA"], country: "Japan" },
  { name: "Kyosho", jpNames: ["京商","KYOSHO"], country: "Japan" },
  { name: "L.L.Bean", jpNames: ["エルエルビーン","L.L.BEAN","LLBEAN","LL BEAN"], country: "USA" },
  { name: "Lacoste", jpNames: ["ラコステ","LACOSTE"], country: "France" },
  { name: "Lalique", jpNames: ["ラリック","LALIQUE"], country: "France" },
  { name: "Levi's", jpNames: ["リーバイス","LEVI'S"], country: "USA" },
  { name: "Lladro", jpNames: ["リヤドロ","LLADRO"], country: "Spain" },
  { name: "Lone Ones", jpNames: ["ロンワンズ","LONE ONES"], country: "USA" },
  { name: "Longchamp", jpNames: ["ロンシャン","LONGCHAMP"], country: "France" },
  { name: "Loree Rodkin", jpNames: ["ローリーロドキン","LOREE RODKIN"], country: "USA" },
  { name: "Luigi Borrelli", jpNames: ["ルイジボレッリ","ルイジ・ボレッリ","LUIGI BORRELLI"], country: "Italy" },
  { name: "Luxman", jpNames: ["ラックスマン","LUXMAN"], country: "Japan" },
  { name: "MCM", jpNames: ["エムシーエム","MCM"], country: "Germany" },
  { name: "Manhattan Portage", jpNames: ["マンハッタンポーテージ","MANHATTAN PORTAGE"], country: "USA" },
  { name: "Marc Jacobs", jpNames: ["マーク・ジェイコブス","MARC JACOBS"], country: "USA" },
  { name: "Martin", jpNames: ["マーティン","MARTIN"], country: "USA" },
  { name: "Mastermind Japan", jpNames: ["マスターマインド","MASTERMIND JAPAN"], country: "Japan" },
  { name: "Meissen", jpNames: ["マイセン","MEISSEN"], country: "Germany" },
  { name: "Michael Kors", jpNames: ["マイケル・コース","MICHAEL KORS"], country: "USA" },
  { name: "Miu Miu", jpNames: ["ミュウミュウ","MIU MIU"], country: "Italy" },
  { name: "Moncler", jpNames: ["モンクレール","MONCLER"], country: "France" },
  { name: "Montbell", jpNames: ["モンベル","MONTBELL"], country: "Japan" },
  { name: "Montblanc", jpNames: ["モンブラン","MONTBLANC"], country: "Germany" },
  { name: "Moog", jpNames: ["モーグ","MOOG"], country: "USA" },
  { name: "Morris", jpNames: ["モーリス","MORRIS"], country: "Japan" },
  { name: "Nakamichi", jpNames: ["ナカミチ","NAKAMICHI"], country: "Japan" },
  { name: "Narumi", jpNames: ["ナルミ","NARUMI"], country: "Japan" },
  { name: "Neighborhood", jpNames: ["ネイバーフッド","NEIGHBORHOOD"], country: "Japan" },
  { name: "Nittaku", jpNames: ["ニッタク","NITTAKU"], country: "Japan" },
  { name: "Niwaka", jpNames: ["俄","NIWAKA"], country: "Japan" },
  { name: "Nojess", jpNames: ["ノジェス","NOJESS"], country: "Japan" },
  { name: "North Face", jpNames: ["ノースフェイス","NORTH FACE"], country: "USA" },
  { name: "Number (N)ine", jpNames: ["ナンバーナイン","NUMBER (N)INE"], country: "Japan" },
  { name: "Off-White", jpNames: ["オフホワイト","OFF-WHITE","OFFWHITE"], country: "Italy" },
  { name: "Okura Art China", jpNames: ["大倉陶園","OKURA ART CHINA"], country: "Japan" },
  { name: "Patagonia", jpNames: ["パタゴニア","PATAGONIA"], country: "USA" },
  { name: "Paul & Joe", jpNames: ["ポール&ジョー","PAUL & JOE","PAUL&JOE"], country: "France" },
  { name: "Playmobil", jpNames: ["プレイモービル","PLAYMOBIL"], country: "Germany" },
  { name: "Pomellato", jpNames: ["ポメラート","POMELLATO"], country: "Italy" },
  { name: "Ponte Vecchio", jpNames: ["ポンテヴェキオ","PONTE VECCHIO"], country: "Japan" },
  { name: "Prince", jpNames: ["プリンス","PRINCE"], country: "USA" },
  { name: "Ralph Lauren", jpNames: ["ラルフローレン","RALPH LAUREN"], country: "USA" },
  { name: "Ray-Ban", jpNames: ["レイバン","RAY-BAN"], country: "USA" },
  { name: "Request", jpNames: ["リクエスト","REQUEST"], country: "Japan" },
  { name: "Rimowa", jpNames: ["リモワ","RIMOWA"], country: "Germany" },
  { name: "SABIAN", jpNames: ["セイビアン","SABIAN"], country: "Canada" },
  { name: "Salvatore Ferragamo", jpNames: ["サルヴァトーレ フェラガモ","フェラガモ","SALVATORE FERRAGAMO","Ferragamo","FERRAGAMO"], country: "Italy" },
  { name: "Saint Laurent Paris", jpNames: ["サンローランパリ","SAINT LAURENT PARIS"], country: "France" },
  { name: "Salsa", jpNames: ["サルサ","SALSA"], country: "USA" },
  { name: "Shinshu", jpNames: ["信州","SHINSHU"], country: "Japan" },
  { name: "Shunjuen", jpNames: ["春秋園","SHUNJUEN"], country: "Japan" },
  { name: "Specialized", jpNames: ["スペシャライズド","SPECIALIZED"], country: "USA" },
  { name: "Star Jewelry", jpNames: ["スタージュエリー","STAR JEWELRY"], country: "Japan" },
  { name: "Stax", jpNames: ["スタックス","STAX"], country: "Japan" },
  { name: "Stella McCartney", jpNames: ["ステラ・マッカートニー","STELLA MCCARTNEY"], country: "UK" },
  { name: "Stone Island", jpNames: ["ストーンアイランド","STONE ISLAND"], country: "Italy" },
  { name: "Stussy", jpNames: ["ステューシー","STUSSY"], country: "USA" },
  { name: "Supreme", jpNames: ["シュプリーム","SUPREME"], country: "USA" },
  { name: "TC Electronic", jpNames: ["ティーシーエレクトロニック","TC ELECTRONIC"], country: "Denmark" },
  { name: "Tachikichi", jpNames: ["たち吉","TACHIKICHI"], country: "Japan" },
  { name: "Tady & King", jpNames: ["タディアンドキング","TADY & KING","TADY&KING"], country: "Japan" },
  { name: "Tascam", jpNames: ["タスカム","TASCAM"], country: "Japan" },
  { name: "Taylor", jpNames: ["テイラー","TAYLOR"], country: "USA" },
  { name: "Teac", jpNames: ["ティアック","TEAC"], country: "Japan" },
  { name: "Technics", jpNames: ["テクニクス","TECHNICS"], country: "Japan" },
  { name: "Timberland", jpNames: ["ティンバーランド","TIMBERLAND"], country: "USA" },
  { name: "Tobe", jpNames: ["砥部焼","TOBE"], country: "Japan" },
  { name: "Tory Burch", jpNames: ["トリーバーチ","TORY BURCH"], country: "USA" },
  { name: "Trek", jpNames: ["トレック","TREK"], country: "USA" },
  { name: "Tumi", jpNames: ["トゥミ","TUMI"], country: "USA" },
  { name: "Undercover", jpNames: ["アンダーカバー","UNDERCOVER"], country: "Japan" },
  { name: "United Arrows", jpNames: ["ユナイテッドアローズ","UNITED ARROWS"], country: "Japan" },
  { name: "Valentino", jpNames: ["ヴァレンティノ","VALENTINO"], country: "Italy" },
  { name: "Vendome Aoyama", jpNames: ["ヴァンドーム青山","VENDOME AOYAMA"], country: "Japan" },
  { name: "Versace", jpNames: ["ヴェルサーチ","VERSACE"], country: "Italy" },
  { name: "Victas", jpNames: ["ヴィクタス","VICTAS"], country: "Japan" },
  { name: "Visvim", jpNames: ["ビズビム","VISVIM"], country: "Japan" },
  { name: "Voigtlander", jpNames: ["フォクトレンダー","VOIGTLANDER"], country: "Germany" },
  { name: "WTAPS", jpNames: ["ダブルタップス","WTAPS"], country: "Japan" },
  { name: "Wedgwood", jpNames: ["ウェッジウッド","WEDGWOOD"], country: "UK" },
  { name: "Wilson", jpNames: ["ウィルソン","WILSON"], country: "USA" },
  { name: "Yashica", jpNames: ["ヤシカ","YASHICA"], country: "Japan" },
  { name: "Yohji Yamamoto", jpNames: ["ヨウジヤマモト","YOHJI YAMAMOTO"], country: "Japan" },
  { name: "Yoshida", jpNames: ["吉田カバン","YOSHIDA"], country: "Japan" },
  { name: "Yumi Katsura", jpNames: ["桂由美","ユミカツラ","YUMI KATSURA"], country: "Japan" },
  { name: "Zoom", jpNames: ["ズーム","ZOOM"], country: "Japan" },
  { name: "master-piece", jpNames: ["マスターピース","MASTER-PIECE","MASTERPIECE"], country: "Japan" },
  { name: "ASICS", jpNames: ["アシックス","ASICS"], country: "Japan" },
  { name: "Adidas", jpNames: ["アディダス","ADIDAS"], country: "Germany" },
  { name: "Birkenstock", jpNames: ["ビルケンシュトック","BIRKENSTOCK"], country: "Germany" },
  { name: "Clarks", jpNames: ["クラークス","CLARKS"], country: "UK" },
  { name: "Converse", jpNames: ["コンバース","CONVERSE"], country: "USA" },
  { name: "Crockett & Jones", jpNames: ["クロケット＆ジョーンズ","CROCKETT & JONES","CROCKETT&JONES"], country: "UK" },
  { name: "Dr. Martens", jpNames: ["ドクターマーチン","DR. MARTENS","DR MARTENS","DRMARTENS"], country: "UK" },
  { name: "Mizuno", jpNames: ["ミズノ","MIZUNO"], country: "Japan" },
  { name: "New Balance", jpNames: ["ニューバランス","NEW BALANCE"], country: "USA" },
  { name: "Nike", jpNames: ["ナイキ","NIKE"], country: "USA" },
  { name: "Onitsuka Tiger", jpNames: ["オニツカタイガー","ONITSUKA TIGER"], country: "Japan" },
  { name: "Puma", jpNames: ["プーマ","PUMA"], country: "Germany" },
  { name: "Reebok", jpNames: ["リーボック","REEBOK"], country: "UK" },
  { name: "Vans", jpNames: ["バンズ","VANS"], country: "USA" },
  { name: "Christian Louboutin", jpNames: ["クリスチャン・ルブタン","CHRISTIAN LOUBOUTIN"], country: "France" },
  { name: "Bronica", jpNames: ["ブロニカ","BRONICA"], country: "Japan" },
  { name: "Canon", jpNames: ["キヤノン","CANON"], country: "Japan" },
  { name: "Contax", jpNames: ["コンタックス","CONTAX"], country: "Germany" },
  { name: "Fujifilm", jpNames: ["富士フイルム","FUJIFILM"], country: "Japan" },
  { name: "Hasselblad", jpNames: ["ハッセルブラッド","HASSELBLAD"], country: "Sweden" },
  { name: "Leica", jpNames: ["ライカ","LEICA"], country: "Germany" },
  { name: "Mamiya", jpNames: ["マミヤ","MAMIYA"], country: "Japan" },
  { name: "Minolta", jpNames: ["ミノルタ","MINOLTA"], country: "Japan" },
  { name: "Nikon", jpNames: ["ニコン","NIKON"], country: "Japan" },
  { name: "Olympus", jpNames: ["オリンパス","OLYMPUS"], country: "Japan" },
  { name: "Pentax", jpNames: ["ペンタックス","PENTAX"], country: "Japan" },
  { name: "Ricoh", jpNames: ["リコー","RICOH"], country: "Japan" },
  { name: "Sigma", jpNames: ["シグマ","SIGMA"], country: "Japan" },
  { name: "Tamron", jpNames: ["タムロン","TAMRON"], country: "Japan" },
  { name: "Tokina", jpNames: ["トキナー","TOKINA"], country: "Japan" },
  { name: "AKG", jpNames: ["アーカーゲー","AKG"], country: "Austria" },
  { name: "Accuphase", jpNames: ["アキュフェーズ","ACCUPHASE"], country: "Japan" },
  { name: "Apple", jpNames: ["アップル","APPLE"], country: "USA" },
  { name: "Audio-Technica", jpNames: ["オーディオテクニカ","AUDIO-TECHNICA","AUDIO TECHNICA","AUDIOTECHNICA"], country: "Japan" },
  { name: "Bose", jpNames: ["ボーズ","BOSE"], country: "USA" },
  { name: "Denon", jpNames: ["デノン","DENON"], country: "Japan" },
  { name: "Esoteric", jpNames: ["エソテリック","ESOTERIC"], country: "Japan" },
  { name: "Focal", jpNames: ["フォーカル","FOCAL"], country: "France" },
  { name: "Foster", jpNames: ["フォスター","FOSTER"], country: "Japan" },
  { name: "Fostex", jpNames: ["フォステクス","FOSTEX"], country: "Japan" },
  { name: "JBL", jpNames: ["ジェイビーエル","JBL"], country: "USA" },
  { name: "Marantz", jpNames: ["マランツ","MARANTZ"], country: "USA" },
  { name: "Onkyo", jpNames: ["オンキヨー","ONKYO"], country: "Japan" },
  { name: "Panasonic", jpNames: ["パナソニック","PANASONIC"], country: "Japan" },
  { name: "Pioneer", jpNames: ["パイオニア","PIONEER"], country: "Japan" },
  { name: "Samsung", jpNames: ["サムスン","SAMSUNG"], country: "South Korea" },
  { name: "Sony", jpNames: ["ソニー","SONY"], country: "Japan" },
  { name: "Battle Spirits", jpNames: ["バトルスピリッツ","BATTLE SPIRITS"], country: "Japan" },
  { name: "Cardfight!! Vanguard", jpNames: ["カードファイト!! ヴァンガード","VANGUARD","CARDFIGHT VANGUARD"], country: "Japan" },
  { name: "Digimon", jpNames: ["デジモン","DIGIMON"], country: "Japan" },
  { name: "Dragon Ball", jpNames: ["ドラゴンボール","DRAGON BALL"], country: "Japan" },
  { name: "Duel Masters", jpNames: ["デュエルマスターズ","DUEL MASTERS"], country: "USA" },
  { name: "Magic: The Gathering", jpNames: ["マジックザギャザリング","MTG"], country: "USA" },
  { name: "One Piece", jpNames: ["ワンピース","ONE PIECE"], country: "Japan" },
  { name: "Pokemon", jpNames: ["ポケモン","POKEMON"], country: "Japan" },
  { name: "Weiss Schwarz", jpNames: ["ヴァイスシュヴァルツ","WEISS SCHWARZ"], country: "Japan" },
  { name: "Yu-Gi-Oh", jpNames: ["遊戯王","YU-GI-OH","YUGIOH"], country: "Japan" },
  { name: "Bandai Namco", jpNames: ["バンダイナムコ","バンナム","BANDAI NAMCO"], country: "Japan" },
  { name: "Capcom", jpNames: ["カプコン","CAPCOM"], country: "Japan" },
  { name: "Konami", jpNames: ["コナミ","KONAMI"], country: "Japan" },
  { name: "Nintendo", jpNames: ["任天堂","ニンテンドー","NINTENDO"], country: "Japan" },
  { name: "Sega", jpNames: ["セガ","SEGA"], country: "Japan" },
  { name: "Sony PlayStation", jpNames: ["プレイステーション","プレステ","PLAYSTATION","PS5","PS4"], country: "Japan" },
  { name: "Square Enix", jpNames: ["スクウェア・エニックス","SQUARE ENIX"], country: "Japan" },
  { name: "Alter", jpNames: ["アルター","ALTER"], country: "Japan" },
  { name: "Bandai", jpNames: ["バンダイ","BANDAI"], country: "Japan" },
  { name: "Banpresto", jpNames: ["バンプレスト","BANPRESTO"], country: "Japan" },
  { name: "Figma", jpNames: ["フィグマ","FIGMA"], country: "Japan" },
  { name: "Funko", jpNames: ["ファンコ","FUNKO"], country: "USA" },
  { name: "Good Smile Company", jpNames: ["グッドスマイルカンパニー","GOOD SMILE COMPANY"], country: "Japan" },
  { name: "Kaiyodo", jpNames: ["海洋堂","KAIYODO"], country: "Japan" },
  { name: "Kotobukiya", jpNames: ["コトブキヤ","KOTOBUKIYA"], country: "Japan" },
  { name: "Max Factory", jpNames: ["マックスファクトリー","MAX FACTORY"], country: "Japan" },
  { name: "Medicom Toy", jpNames: ["メディコムトイ","MEDICOM TOY"], country: "Japan" },
  { name: "MegaHouse", jpNames: ["メガハウス","MEGAHOUSE"], country: "Japan" },
  { name: "Nendoroid", jpNames: ["ねんどろいど","NENDOROID"], country: "Japan" },
  { name: "S.H.Figuarts", jpNames: ["S.H.フィギュアーツ","S.H.FIGUARTS","SHFIGUARTS","SH FIGUARTS"], country: "Japan" },
  { name: "Arita", jpNames: ["有田焼","ARITA"], country: "Japan" },
  { name: "Baccarat", jpNames: ["バカラ","BACCARAT"], country: "France" },
  { name: "Bizen", jpNames: ["備前焼","BIZEN"], country: "Japan" },
  { name: "Hagi", jpNames: ["萩焼","HAGI"], country: "Japan" },
  { name: "Imari", jpNames: ["伊万里焼","IMARI"], country: "Japan" },
  { name: "Kakiemon", jpNames: ["柿右衛門","KAKIEMON"], country: "Japan" },
  { name: "Kutani", jpNames: ["九谷焼","KUTANI"], country: "Japan" },
  { name: "Mashiko", jpNames: ["益子焼","MASHIKO"], country: "Japan" },
  { name: "Mino", jpNames: ["美濃焼","MINO"], country: "Japan" },
  { name: "Nabeshima", jpNames: ["鍋島焼","NABESHIMA"], country: "Japan" },
  { name: "Noritake", jpNames: ["ノリタケ","NORITAKE"], country: "Japan" },
  { name: "Satsuma", jpNames: ["薩摩焼","SATSUMA"], country: "Japan" },
  { name: "Shigaraki", jpNames: ["信楽焼","SHIGARAKI"], country: "Japan" },
  { name: "Ampeg", jpNames: ["アンペグ","AMPEG"], country: "USA" },
  { name: "Aria", jpNames: ["アリア","ARIA"], country: "Japan" },
  { name: "Boss", jpNames: ["ボス","BOSS"], country: "Japan" },
  { name: "ESP", jpNames: ["イーエスピー","ESP"], country: "Japan" },
  { name: "Edwards", jpNames: ["エドワーズ","EDWARDS"], country: "Japan" },
  { name: "Fender", jpNames: ["フェンダー","FENDER"], country: "USA" },
  { name: "Fernandes", jpNames: ["フェルナンデス","FERNANDES"], country: "Japan" },
  { name: "Fujigen", jpNames: ["フジゲン","FUJIGEN"], country: "Japan" },
  { name: "Ibanez", jpNames: ["アイバニーズ","IBANEZ"], country: "Japan" },
  { name: "Korg", jpNames: ["コルグ","KORG"], country: "Japan" },
  { name: "Roland", jpNames: ["ローランド","ROLAND"], country: "Japan" },
  { name: "Takamine", jpNames: ["タカミネ","TAKAMINE"], country: "Japan" },
  { name: "Tokai", jpNames: ["東海楽器","TOKAI"], country: "Japan" },
  { name: "Yamaha", jpNames: ["ヤマハ","YAMAHA"], country: "Japan" },
  { name: "Asics", jpNames: ["アシックス","ASICS"], country: "Japan" },
  { name: "Butterfly", jpNames: ["バタフライ","BUTTERFLY"], country: "Japan", categories: ["Sporting Goods"] },
  { name: "Callaway", jpNames: ["キャロウェイ","CALLAWAY"], country: "USA" },
  { name: "Daiwa", jpNames: ["ダイワ","DAIWA"], country: "Japan" },
  { name: "Descente", jpNames: ["デサント","DESCENTE"], country: "Japan" },
  { name: "Gamakatsu", jpNames: ["がまかつ","GAMAKATSU"], country: "Japan" },
  { name: "Pearl Izumi", jpNames: ["パールイズミ","PEARL IZUMI"], country: "Japan" },
  { name: "Ping", jpNames: ["ピン","PING"], country: "USA" },
  { name: "Shimano", jpNames: ["シマノ","SHIMANO"], country: "Japan" },
  { name: "TaylorMade", jpNames: ["テーラーメイド","TAYLORMADE"], country: "USA" },
  { name: "Titleist", jpNames: ["タイトリスト","TITLEIST"], country: "USA" },
  { name: "Yonex", jpNames: ["ヨネックス","YONEX"], country: "Japan" },
  { name: "Honda", jpNames: ["ホンダ","HONDA"], country: "Japan" },
  { name: "Nissan", jpNames: ["日産","ニッサン","NISSAN"], country: "Japan" },
  { name: "Toyota", jpNames: ["トヨタ","TOYOTA"], country: "Japan" },
  { name: "KOSE", jpNames: ["コーセー","KOSE"], country: "Japan" },
  { name: "SK-II", jpNames: ["エスケーツー","SK-II","SK2"], country: "Japan" },
  { name: "Shiseido", jpNames: ["資生堂","シセイドウ","SHISEIDO"], country: "Japan" },
  { name: "Aoshima", jpNames: ["アオシマ","AOSHIMA"], country: "Japan" },
  { name: "Fujimi", jpNames: ["フジミ","FUJIMI"], country: "Japan" },
  { name: "Gundam (Gunpla)", jpNames: ["ガンダム","ガンプラ","GUNDAM","GUNPLA"], country: "Japan" },
  { name: "Hasegawa", jpNames: ["ハセガワ","HASEGAWA"], country: "Japan" },
  { name: "Hot Toys", jpNames: ["ホットトイズ","HOT TOYS"], country: "Hong Kong" },
  { name: "LEGO", jpNames: ["レゴ","LEGO"], country: "Denmark" },
  { name: "Takara Tomy", jpNames: ["タカラトミー","TAKARA TOMY"], country: "Japan" },
  { name: "Tamiya", jpNames: ["タミヤ","TAMIYA"], country: "Japan" },
  { name: "Tomica", jpNames: ["トミカ","TOMICA"], country: "Japan" },
  { name: "Peterson", jpNames: ["ピーターソン"], country: "Ireland", categories: ["Pipes"] },
  { name: "Savinelli", jpNames: ["サビネリ"], country: "Italy", categories: ["Pipes"] },
  { name: "Stanwell", jpNames: ["スタンウェル"], country: "Denmark", categories: ["Pipes"] },
  { name: "Chacom", jpNames: ["シャコム"], country: "France", categories: ["Pipes"] },
  { name: "Butz-Choquin", jpNames: ["ビュッツショカン","BUTZ CHOQUIN"], country: "France", categories: ["Pipes"] },
  { name: "Vauen", jpNames: ["ファウエン"], country: "Germany", categories: ["Pipes"] },
  { name: "Brebbia", jpNames: ["ブレビア"], country: "Italy", categories: ["Pipes"] },
  { name: "Nording", jpNames: ["ノルディング"], country: "Denmark", categories: ["Pipes"] },
  { name: "Tsuge", jpNames: ["ツゲ","柘","柘製作所","TSUGE"], country: "Japan", categories: ["Pipes"] },
  { name: "Castello", jpNames: ["カステロ"], country: "Italy", categories: ["Pipes"] },
  { name: "Ser Jacopo", jpNames: ["セルヤコポ"], country: "Italy", categories: ["Pipes"] },
  { name: "Radice", jpNames: ["ラディーチェ"], country: "Italy", categories: ["Pipes"] },
  { name: "Kaywoodie", jpNames: ["ケイウッディ"], country: "USA", categories: ["Pipes"] },
  { name: "Dr. Grabow", jpNames: ["ドクターグラボウ","DR GRABOW"], country: "USA", categories: ["Pipes"] },
  { name: "Missouri Meerschaum", jpNames: ["ミズーリメシャム"], country: "USA", categories: ["Pipes"] },
  { name: "Brigham", jpNames: ["ブリガム"], country: "Canada", categories: ["Pipes"] },
  { name: "Ropp", jpNames: ["ロップ"], country: "France", categories: ["Pipes"] },
  { name: "Winslow", jpNames: ["ウィンスロー"], country: "Denmark", categories: ["Pipes"] },
  { name: "Ben Wade", jpNames: ["ベンウェイド"], country: "UK", categories: ["Pipes"] },
  { name: "Il Ceppo", jpNames: ["イルチェッポ"], country: "Italy", categories: ["Pipes"] },
  { name: "Caminetto", jpNames: ["カミネット"], country: "Italy", categories: ["Pipes"] },
  { name: "Medico", jpNames: ["メディコ"], country: "USA", categories: ["Pipes"] },
];

async function seedItemSpecificsFields() {
  console.log('Seeding ItemSpecificsField...');
  let count = 0;
  for (const field of INITIAL_DATA) {
    await prisma.itemSpecificsField.upsert({
      where: {
        category_fieldName: {
          category: field.category,
          fieldName: field.fieldName,
        },
      },
      create: {
        category: field.category,
        tagJp: field.tagJp,
        fieldName: field.fieldName,
        fieldType: field.fieldType,
        priority: field.priority,
        notes: field.notes || null,
      },
      update: {
        tagJp: field.tagJp,
        fieldType: field.fieldType,
        priority: field.priority,
        notes: field.notes || null,
      },
    });
    count++;
  }
  console.log(`  ItemSpecificsField: ${count} records upserted`);
}

async function seedBrands() {
  console.log('Seeding Brand...');
  let count = 0;
  for (const brand of BRAND_DATA) {
    await prisma.brand.upsert({
      where: { name: brand.name },
      create: {
        name: brand.name,
        jpNames: brand.jpNames,
        country: brand.country || null,
        parentBrand: brand.parentBrand || null,
        categories: brand.categories || [],
        isMaterial: brand.isMaterial || false,
      },
      update: {
        jpNames: brand.jpNames,
        country: brand.country || null,
        parentBrand: brand.parentBrand || null,
        categories: brand.categories || [],
        isMaterial: brand.isMaterial || false,
      },
    });
    count++;
  }
  console.log(`  Brand: ${count} records upserted`);
}

async function main() {
  console.log('Starting Item Specifics seed...');
  await seedItemSpecificsFields();
  await seedBrands();
  console.log('Seed complete!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

